apiVersion: waf.kubewaf.io/v1beta1
kind: WAF
metadata:
  labels:
    app.kubernetes.io/name: kubewaf
    app.kubernetes.io/managed-by: kustomize
  name: waf-sample
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: backend

  ruleRefs:
    - kind: "RuleSet"
      name: ruleset-crs
      namespace: default
      group: "waf.kubewaf.io"
      version: "v1beta1"

