apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-ecds
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: ecds
spec:
  type: ClusterIP
  ports:
    - name: ecds
      port: {{ .Values.dataplane.ecds.port | default 18001 }}
      targetPort: ecds
      protocol: TCP
    - name: extension
      port: {{ .Values.dataplane.extensionServer.port | default 5005 }}
      targetPort: extension
      protocol: TCP
    - name: wasm
      port: {{ .Values.dataplane.wasmServe.port | default 18002 }}
      targetPort: wasm
      protocol: TCP
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
