//go:build !ignore_autogenerated

/*
Copyright 2025 Buzz-IT GmbH.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Probe) DeepCopyInto(out *Probe) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Probe.
func (in *Probe) DeepCopy() *Probe {
	if in == nil {
		return nil
	}
	out := new(Probe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Probe) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeAnomaly) DeepCopyInto(out *ProbeAnomaly) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeAnomaly.
func (in *ProbeAnomaly) DeepCopy() *ProbeAnomaly {
	if in == nil {
		return nil
	}
	out := new(ProbeAnomaly)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeAssembly) DeepCopyInto(out *ProbeAssembly) {
	*out = *in
	if in.DroppedDataFiles != nil {
		in, out := &in.DroppedDataFiles, &out.DroppedDataFiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeAssembly.
func (in *ProbeAssembly) DeepCopy() *ProbeAssembly {
	if in == nil {
		return nil
	}
	out := new(ProbeAssembly)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeHTTPView) DeepCopyInto(out *ProbeHTTPView) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeHTTPView.
func (in *ProbeHTTPView) DeepCopy() *ProbeHTTPView {
	if in == nil {
		return nil
	}
	out := new(ProbeHTTPView)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeInterruption) DeepCopyInto(out *ProbeInterruption) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeInterruption.
func (in *ProbeInterruption) DeepCopy() *ProbeInterruption {
	if in == nil {
		return nil
	}
	out := new(ProbeInterruption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeMatch) DeepCopyInto(out *ProbeMatch) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeMatch.
func (in *ProbeMatch) DeepCopy() *ProbeMatch {
	if in == nil {
		return nil
	}
	out := new(ProbeMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeRequestEcho) DeepCopyInto(out *ProbeRequestEcho) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeRequestEcho.
func (in *ProbeRequestEcho) DeepCopy() *ProbeRequestEcho {
	if in == nil {
		return nil
	}
	out := new(ProbeRequestEcho)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeStatus) DeepCopyInto(out *ProbeStatus) {
	*out = *in
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(ProbeTarget)
		**out = **in
	}
	if in.RequestEcho != nil {
		in, out := &in.RequestEcho, &out.RequestEcho
		*out = new(ProbeRequestEcho)
		**out = **in
	}
	if in.Assembly != nil {
		in, out := &in.Assembly, &out.Assembly
		*out = new(ProbeAssembly)
		(*in).DeepCopyInto(*out)
	}
	if in.Interruption != nil {
		in, out := &in.Interruption, &out.Interruption
		*out = new(ProbeInterruption)
		**out = **in
	}
	if in.Anomaly != nil {
		in, out := &in.Anomaly, &out.Anomaly
		*out = new(ProbeAnomaly)
		**out = **in
	}
	if in.Matches != nil {
		in, out := &in.Matches, &out.Matches
		*out = make([]ProbeMatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(ProbeHTTPView)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeStatus.
func (in *ProbeStatus) DeepCopy() *ProbeStatus {
	if in == nil {
		return nil
	}
	out := new(ProbeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeTarget) DeepCopyInto(out *ProbeTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeTarget.
func (in *ProbeTarget) DeepCopy() *ProbeTarget {
	if in == nil {
		return nil
	}
	out := new(ProbeTarget)
	in.DeepCopyInto(out)
	return out
}
