// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package convert

import (
	types "github.com/coreruleset/crslang/types"
	v1beta1 "github.com/kubewaf-io/kubewaf/api/seclang/v1beta1"
)

type OperatorMapperImpl struct{}

func (c *OperatorMapperImpl) Convert(source v1beta1.OperatorType) types.OperatorType {
	var typesOperatorType types.OperatorType
	switch source {
	case v1beta1.BeginsWith:
		typesOperatorType = types.BeginsWith
	case v1beta1.Contains:
		typesOperatorType = types.Contains
	case v1beta1.ContainsWord:
		typesOperatorType = types.ContainsWord
	case v1beta1.DetectSQLi:
		typesOperatorType = types.DetectSQLi
	case v1beta1.DetectXSS:
		typesOperatorType = types.DetectXSS
	case v1beta1.EndsWith:
		typesOperatorType = types.EndsWith
	case v1beta1.Eq:
		typesOperatorType = types.Eq
	case v1beta1.FuzzyHash:
		typesOperatorType = types.FuzzyHash
	case v1beta1.Ge:
		typesOperatorType = types.Ge
	case v1beta1.GeoLookup:
		typesOperatorType = types.GeoLookup
	case v1beta1.GsbLookup:
		typesOperatorType = types.GsbLookup
	case v1beta1.Gt:
		typesOperatorType = types.Gt
	case v1beta1.InspectFile:
		typesOperatorType = types.InspectFile
	case v1beta1.IpMatch:
		typesOperatorType = types.IpMatch
	case v1beta1.IpMatchF:
		typesOperatorType = types.IpMatchF
	case v1beta1.IpMatchFromFile:
		typesOperatorType = types.IpMatchFromFile
	case v1beta1.Le:
		typesOperatorType = types.Le
	case v1beta1.Lt:
		typesOperatorType = types.Lt
	case v1beta1.Pm:
		typesOperatorType = types.Pm
	case v1beta1.PmFromFile:
		typesOperatorType = types.PmFromFile
	case v1beta1.Pmf:
		typesOperatorType = types.Pmf
	case v1beta1.Rbl:
		typesOperatorType = types.Rbl
	case v1beta1.Rsub:
		typesOperatorType = types.Rsub
	case v1beta1.Rx:
		typesOperatorType = types.Rx
	case v1beta1.RxGlobal:
		typesOperatorType = types.RxGlobal
	case v1beta1.StrEq:
		typesOperatorType = types.StrEq
	case v1beta1.StrMatch:
		typesOperatorType = types.StrMatch
	case v1beta1.UnconditionalMatch:
		typesOperatorType = types.UnconditionalMatch
	case v1beta1.UnknownOperator:
		typesOperatorType = types.UnknownOperator
	case v1beta1.ValidateByteRange:
		typesOperatorType = types.ValidateByteRange
	case v1beta1.ValidateDTD:
		typesOperatorType = types.ValidateDTD
	case v1beta1.ValidateHash:
		typesOperatorType = types.ValidateHash
	case v1beta1.ValidateSchema:
		typesOperatorType = types.ValidateSchema
	case v1beta1.ValidateUrlEncoding:
		typesOperatorType = types.ValidateUrlEncoding
	case v1beta1.ValidateUtf8Encoding:
		typesOperatorType = types.ValidateUtf8Encoding
	case v1beta1.VerifyCC:
		typesOperatorType = types.VerifyCC
	case v1beta1.VerifyCPF:
		typesOperatorType = types.VerifyCPF
	case v1beta1.VerifySSN:
		typesOperatorType = types.VerifySSN
	case v1beta1.VerifySVNR:
		typesOperatorType = types.VerifySVNR
	case v1beta1.Within:
		typesOperatorType = types.Within
	default:
		typesOperatorType = types.Eq
	}
	return typesOperatorType
}

type OperatorReverseMapperImpl struct{}

func (c *OperatorReverseMapperImpl) Convert(source types.OperatorType) v1beta1.OperatorType {
	var v1beta1OperatorType v1beta1.OperatorType
	switch source {
	case types.BeginsWith:
		v1beta1OperatorType = v1beta1.BeginsWith
	case types.Contains:
		v1beta1OperatorType = v1beta1.Contains
	case types.ContainsWord:
		v1beta1OperatorType = v1beta1.ContainsWord
	case types.DetectSQLi:
		v1beta1OperatorType = v1beta1.DetectSQLi
	case types.DetectXSS:
		v1beta1OperatorType = v1beta1.DetectXSS
	case types.EndsWith:
		v1beta1OperatorType = v1beta1.EndsWith
	case types.Eq:
		v1beta1OperatorType = v1beta1.Eq
	case types.FuzzyHash:
		v1beta1OperatorType = v1beta1.FuzzyHash
	case types.Ge:
		v1beta1OperatorType = v1beta1.Ge
	case types.GeoLookup:
		v1beta1OperatorType = v1beta1.GeoLookup
	case types.GsbLookup:
		v1beta1OperatorType = v1beta1.GsbLookup
	case types.Gt:
		v1beta1OperatorType = v1beta1.Gt
	case types.InspectFile:
		v1beta1OperatorType = v1beta1.InspectFile
	case types.IpMatch:
		v1beta1OperatorType = v1beta1.IpMatch
	case types.IpMatchF:
		v1beta1OperatorType = v1beta1.IpMatchF
	case types.IpMatchFromFile:
		v1beta1OperatorType = v1beta1.IpMatchFromFile
	case types.Le:
		v1beta1OperatorType = v1beta1.Le
	case types.Lt:
		v1beta1OperatorType = v1beta1.Lt
	case types.Pm:
		v1beta1OperatorType = v1beta1.Pm
	case types.PmFromFile:
		v1beta1OperatorType = v1beta1.PmFromFile
	case types.Pmf:
		v1beta1OperatorType = v1beta1.Pmf
	case types.Rbl:
		v1beta1OperatorType = v1beta1.Rbl
	case types.Rsub:
		v1beta1OperatorType = v1beta1.Rsub
	case types.Rx:
		v1beta1OperatorType = v1beta1.Rx
	case types.RxGlobal:
		v1beta1OperatorType = v1beta1.RxGlobal
	case types.StrEq:
		v1beta1OperatorType = v1beta1.StrEq
	case types.StrMatch:
		v1beta1OperatorType = v1beta1.StrMatch
	case types.UnconditionalMatch:
		v1beta1OperatorType = v1beta1.UnconditionalMatch
	case types.UnknownOperator:
		v1beta1OperatorType = v1beta1.UnknownOperator
	case types.ValidateByteRange:
		v1beta1OperatorType = v1beta1.ValidateByteRange
	case types.ValidateDTD:
		v1beta1OperatorType = v1beta1.ValidateDTD
	case types.ValidateHash:
		v1beta1OperatorType = v1beta1.ValidateHash
	case types.ValidateSchema:
		v1beta1OperatorType = v1beta1.ValidateSchema
	case types.ValidateUrlEncoding:
		v1beta1OperatorType = v1beta1.ValidateUrlEncoding
	case types.ValidateUtf8Encoding:
		v1beta1OperatorType = v1beta1.ValidateUtf8Encoding
	case types.VerifyCC:
		v1beta1OperatorType = v1beta1.VerifyCC
	case types.VerifyCPF:
		v1beta1OperatorType = v1beta1.VerifyCPF
	case types.VerifySSN:
		v1beta1OperatorType = v1beta1.VerifySSN
	case types.VerifySVNR:
		v1beta1OperatorType = v1beta1.VerifySVNR
	case types.Within:
		v1beta1OperatorType = v1beta1.Within
	default: // ignored
	}
	return v1beta1OperatorType
}
