// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package convert

import (
	types "github.com/coreruleset/crslang/types"
	v1beta1 "github.com/kubewaf-io/kubewaf/api/seclang/v1beta1"
)

type CollectionMapperImpl struct{}

func (c *CollectionMapperImpl) Convert(source v1beta1.CollectionName) types.CollectionName {
	var typesCollectionName types.CollectionName
	switch source {
	case v1beta1.ARGS:
		typesCollectionName = types.ARGS
	case v1beta1.ARGS_GET:
		typesCollectionName = types.ARGS_GET
	case v1beta1.ARGS_GET_NAMES:
		typesCollectionName = types.ARGS_GET_NAMES
	case v1beta1.ARGS_NAMES:
		typesCollectionName = types.ARGS_NAMES
	case v1beta1.ARGS_POST:
		typesCollectionName = types.ARGS_POST
	case v1beta1.ARGS_POST_NAMES:
		typesCollectionName = types.ARGS_POST_NAMES
	case v1beta1.ENV:
		typesCollectionName = types.ENV
	case v1beta1.FILES:
		typesCollectionName = types.FILES
	case v1beta1.GEO:
		typesCollectionName = types.GEO
	case v1beta1.GLOBAL:
		typesCollectionName = types.GLOBAL
	case v1beta1.IP:
		typesCollectionName = types.IP
	case v1beta1.MATCHED_VARS:
		typesCollectionName = types.MATCHED_VARS
	case v1beta1.MATCHED_VARS_NAMES:
		typesCollectionName = types.MATCHED_VARS_NAMES
	case v1beta1.MULTIPART_PART_HEADERS:
		typesCollectionName = types.MULTIPART_PART_HEADERS
	case v1beta1.PERF_RULES:
		typesCollectionName = types.PERF_RULES
	case v1beta1.REQUEST_COOKIES:
		typesCollectionName = types.REQUEST_COOKIES
	case v1beta1.REQUEST_COOKIES_NAMES:
		typesCollectionName = types.REQUEST_COOKIES_NAMES
	case v1beta1.REQUEST_HEADERS:
		typesCollectionName = types.REQUEST_HEADERS
	case v1beta1.REQUEST_HEADERS_NAMES:
		typesCollectionName = types.REQUEST_HEADERS_NAMES
	case v1beta1.RESOURCE:
		typesCollectionName = types.RESOURCE
	case v1beta1.RESPONSE_HEADERS:
		typesCollectionName = types.RESPONSE_HEADERS
	case v1beta1.RESPONSE_HEADERS_NAMES:
		typesCollectionName = types.RESPONSE_HEADERS_NAMES
	case v1beta1.RULE:
		typesCollectionName = types.RULE
	case v1beta1.SESSION:
		typesCollectionName = types.SESSION
	case v1beta1.TX:
		typesCollectionName = types.TX
	case v1beta1.UNKNOWN_COLLECTION:
		typesCollectionName = types.UNKNOWN_COLLECTION
	case v1beta1.USER:
		typesCollectionName = types.USER
	case v1beta1.XML:
		typesCollectionName = types.XML
	default:
		typesCollectionName = types.UNKNOWN_COLLECTION
	}
	return typesCollectionName
}

type CollectionReverseMapperImpl struct{}

func (c *CollectionReverseMapperImpl) Convert(source types.CollectionName) v1beta1.CollectionName {
	var v1beta1CollectionName v1beta1.CollectionName
	switch source {
	case types.ARGS:
		v1beta1CollectionName = v1beta1.ARGS
	case types.ARGS_GET:
		v1beta1CollectionName = v1beta1.ARGS_GET
	case types.ARGS_GET_NAMES:
		v1beta1CollectionName = v1beta1.ARGS_GET_NAMES
	case types.ARGS_NAMES:
		v1beta1CollectionName = v1beta1.ARGS_NAMES
	case types.ARGS_POST:
		v1beta1CollectionName = v1beta1.ARGS_POST
	case types.ARGS_POST_NAMES:
		v1beta1CollectionName = v1beta1.ARGS_POST_NAMES
	case types.ENV:
		v1beta1CollectionName = v1beta1.ENV
	case types.FILES:
		v1beta1CollectionName = v1beta1.FILES
	case types.GEO:
		v1beta1CollectionName = v1beta1.GEO
	case types.GLOBAL:
		v1beta1CollectionName = v1beta1.GLOBAL
	case types.IP:
		v1beta1CollectionName = v1beta1.IP
	case types.MATCHED_VARS:
		v1beta1CollectionName = v1beta1.MATCHED_VARS
	case types.MATCHED_VARS_NAMES:
		v1beta1CollectionName = v1beta1.MATCHED_VARS_NAMES
	case types.MULTIPART_PART_HEADERS:
		v1beta1CollectionName = v1beta1.MULTIPART_PART_HEADERS
	case types.PERF_RULES:
		v1beta1CollectionName = v1beta1.PERF_RULES
	case types.REQUEST_COOKIES:
		v1beta1CollectionName = v1beta1.REQUEST_COOKIES
	case types.REQUEST_COOKIES_NAMES:
		v1beta1CollectionName = v1beta1.REQUEST_COOKIES_NAMES
	case types.REQUEST_HEADERS:
		v1beta1CollectionName = v1beta1.REQUEST_HEADERS
	case types.REQUEST_HEADERS_NAMES:
		v1beta1CollectionName = v1beta1.REQUEST_HEADERS_NAMES
	case types.RESOURCE:
		v1beta1CollectionName = v1beta1.RESOURCE
	case types.RESPONSE_HEADERS:
		v1beta1CollectionName = v1beta1.RESPONSE_HEADERS
	case types.RESPONSE_HEADERS_NAMES:
		v1beta1CollectionName = v1beta1.RESPONSE_HEADERS_NAMES
	case types.RULE:
		v1beta1CollectionName = v1beta1.RULE
	case types.SESSION:
		v1beta1CollectionName = v1beta1.SESSION
	case types.TX:
		v1beta1CollectionName = v1beta1.TX
	case types.UNKNOWN_COLLECTION:
		v1beta1CollectionName = v1beta1.UNKNOWN_COLLECTION
	case types.USER:
		v1beta1CollectionName = v1beta1.USER
	case types.XML:
		v1beta1CollectionName = v1beta1.XML
	default:
		v1beta1CollectionName = v1beta1.UNKNOWN_COLLECTION
	}
	return v1beta1CollectionName
}
