// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package convert

import (
	types "github.com/coreruleset/crslang/types"
	v1beta1 "github.com/kubewaf-io/kubewaf/api/seclang/v1beta1"
)

type VariableMapperImpl struct{}

func (c *VariableMapperImpl) Convert(source v1beta1.VariableName) types.VariableName {
	var typesVariableName types.VariableName
	switch source {
	case v1beta1.ARGS_COMBINED_SIZE:
		typesVariableName = types.ARGS_COMBINED_SIZE
	case v1beta1.AUTH_TYPE:
		typesVariableName = types.AUTH_TYPE
	case v1beta1.DURATION:
		typesVariableName = types.DURATION
	case v1beta1.FILES_COMBINED_SIZE:
		typesVariableName = types.FILES_COMBINED_SIZE
	case v1beta1.FILES_NAMES:
		typesVariableName = types.FILES_NAMES
	case v1beta1.FILES_SIZES:
		typesVariableName = types.FILES_SIZES
	case v1beta1.FILES_TMPNAMES:
		typesVariableName = types.FILES_TMPNAMES
	case v1beta1.FILES_TMP_CONTENT:
		typesVariableName = types.FILES_TMP_CONTENT
	case v1beta1.FULL_REQUEST:
		typesVariableName = types.FULL_REQUEST
	case v1beta1.FULL_REQUEST_LENGTH:
		typesVariableName = types.FULL_REQUEST_LENGTH
	case v1beta1.HIGHEST_SEVERITY:
		typesVariableName = types.HIGHEST_SEVERITY
	case v1beta1.INBOUND_DATA_ERROR:
		typesVariableName = types.INBOUND_DATA_ERROR
	case v1beta1.MATCHED_VAR:
		typesVariableName = types.MATCHED_VAR
	case v1beta1.MATCHED_VAR_NAME:
		typesVariableName = types.MATCHED_VAR_NAME
	case v1beta1.MODSEC_BUILD:
		typesVariableName = types.MODSEC_BUILD
	case v1beta1.MSC_PCRE_ERROR:
		typesVariableName = types.MSC_PCRE_ERROR
	case v1beta1.MSC_PCRE_LIMITS_EXCEEDED:
		typesVariableName = types.MSC_PCRE_LIMITS_EXCEEDED
	case v1beta1.MULTIPART_BOUNDARY_QUOTED:
		typesVariableName = types.MULTIPART_BOUNDARY_QUOTED
	case v1beta1.MULTIPART_BOUNDARY_WHITESPACE:
		typesVariableName = types.MULTIPART_BOUNDARY_WHITESPACE
	case v1beta1.MULTIPART_CRLF_LF_LINES:
		typesVariableName = types.MULTIPART_CRLF_LF_LINES
	case v1beta1.MULTIPART_DATA_AFTER:
		typesVariableName = types.MULTIPART_DATA_AFTER
	case v1beta1.MULTIPART_DATA_BEFORE:
		typesVariableName = types.MULTIPART_DATA_BEFORE
	case v1beta1.MULTIPART_FILENAME:
		typesVariableName = types.MULTIPART_FILENAME
	case v1beta1.MULTIPART_FILE_LIMIT_EXCEEDED:
		typesVariableName = types.MULTIPART_FILE_LIMIT_EXCEEDED
	case v1beta1.MULTIPART_HEADER_FOLDING:
		typesVariableName = types.MULTIPART_HEADER_FOLDING
	case v1beta1.MULTIPART_INVALID_HEADER_FOLDING:
		typesVariableName = types.MULTIPART_INVALID_HEADER_FOLDING
	case v1beta1.MULTIPART_INVALID_PART:
		typesVariableName = types.MULTIPART_INVALID_PART
	case v1beta1.MULTIPART_INVALID_QUOTING:
		typesVariableName = types.MULTIPART_INVALID_QUOTING
	case v1beta1.MULTIPART_LF_LINE:
		typesVariableName = types.MULTIPART_LF_LINE
	case v1beta1.MULTIPART_MISSING_SEMICOLON:
		typesVariableName = types.MULTIPART_MISSING_SEMICOLON
	case v1beta1.MULTIPART_NAME:
		typesVariableName = types.MULTIPART_NAME
	case v1beta1.MULTIPART_SEMICOLON_MISSING:
		typesVariableName = types.MULTIPART_SEMICOLON_MISSING
	case v1beta1.MULTIPART_STRICT_ERROR:
		typesVariableName = types.MULTIPART_STRICT_ERROR
	case v1beta1.MULTIPART_UNMATCHED_BOUNDARY:
		typesVariableName = types.MULTIPART_UNMATCHED_BOUNDARY
	case v1beta1.OUTBOUND_DATA_ERROR:
		typesVariableName = types.OUTBOUND_DATA_ERROR
	case v1beta1.PATH_INFO:
		typesVariableName = types.PATH_INFO
	case v1beta1.PERF_ALL:
		typesVariableName = types.PERF_ALL
	case v1beta1.PERF_COMBINED:
		typesVariableName = types.PERF_COMBINED
	case v1beta1.PERF_GC:
		typesVariableName = types.PERF_GC
	case v1beta1.PERF_LOGGING:
		typesVariableName = types.PERF_LOGGING
	case v1beta1.PERF_PHASE1:
		typesVariableName = types.PERF_PHASE1
	case v1beta1.PERF_PHASE2:
		typesVariableName = types.PERF_PHASE2
	case v1beta1.PERF_PHASE3:
		typesVariableName = types.PERF_PHASE3
	case v1beta1.PERF_PHASE4:
		typesVariableName = types.PERF_PHASE4
	case v1beta1.PERF_PHASE5:
		typesVariableName = types.PERF_PHASE5
	case v1beta1.PERF_SREAD:
		typesVariableName = types.PERF_SREAD
	case v1beta1.PERF_SWRITE:
		typesVariableName = types.PERF_SWRITE
	case v1beta1.QUERY_STRING:
		typesVariableName = types.QUERY_STRING
	case v1beta1.REMOTE_ADDR:
		typesVariableName = types.REMOTE_ADDR
	case v1beta1.REMOTE_HOST:
		typesVariableName = types.REMOTE_HOST
	case v1beta1.REMOTE_PORT:
		typesVariableName = types.REMOTE_PORT
	case v1beta1.REMOTE_USER:
		typesVariableName = types.REMOTE_USER
	case v1beta1.REQBODY_ERROR:
		typesVariableName = types.REQBODY_ERROR
	case v1beta1.REQBODY_ERROR_MSG:
		typesVariableName = types.REQBODY_ERROR_MSG
	case v1beta1.REQBODY_PROCESSOR:
		typesVariableName = types.REQBODY_PROCESSOR
	case v1beta1.REQBODY_PROCESSOR_ERROR:
		typesVariableName = types.REQBODY_PROCESSOR_ERROR
	case v1beta1.REQBODY_PROCESSOR_ERROR_MSG:
		typesVariableName = types.REQBODY_PROCESSOR_ERROR_MSG
	case v1beta1.REQUEST_BASENAME:
		typesVariableName = types.REQUEST_BASENAME
	case v1beta1.REQUEST_BODY:
		typesVariableName = types.REQUEST_BODY
	case v1beta1.REQUEST_BODY_LENGTH:
		typesVariableName = types.REQUEST_BODY_LENGTH
	case v1beta1.REQUEST_FILENAME:
		typesVariableName = types.REQUEST_FILENAME
	case v1beta1.REQUEST_LINE:
		typesVariableName = types.REQUEST_LINE
	case v1beta1.REQUEST_METHOD:
		typesVariableName = types.REQUEST_METHOD
	case v1beta1.REQUEST_PROTOCOL:
		typesVariableName = types.REQUEST_PROTOCOL
	case v1beta1.REQUEST_URI:
		typesVariableName = types.REQUEST_URI
	case v1beta1.REQUEST_URI_RAW:
		typesVariableName = types.REQUEST_URI_RAW
	case v1beta1.RESPONSE_BODY:
		typesVariableName = types.RESPONSE_BODY
	case v1beta1.RESPONSE_CONTENT_LENGTH:
		typesVariableName = types.RESPONSE_CONTENT_LENGTH
	case v1beta1.RESPONSE_CONTENT_TYPE:
		typesVariableName = types.RESPONSE_CONTENT_TYPE
	case v1beta1.RESPONSE_PROTOCOL:
		typesVariableName = types.RESPONSE_PROTOCOL
	case v1beta1.RESPONSE_STATUS:
		typesVariableName = types.RESPONSE_STATUS
	case v1beta1.SCRIPT_BASENAME:
		typesVariableName = types.SCRIPT_BASENAME
	case v1beta1.SCRIPT_FILENAME:
		typesVariableName = types.SCRIPT_FILENAME
	case v1beta1.SCRIPT_GID:
		typesVariableName = types.SCRIPT_GID
	case v1beta1.SCRIPT_GROUPNAME:
		typesVariableName = types.SCRIPT_GROUPNAME
	case v1beta1.SCRIPT_MODE:
		typesVariableName = types.SCRIPT_MODE
	case v1beta1.SCRIPT_UID:
		typesVariableName = types.SCRIPT_UID
	case v1beta1.SCRIPT_USERNAME:
		typesVariableName = types.SCRIPT_USERNAME
	case v1beta1.SDBM_DELETE_ERROR:
		typesVariableName = types.SDBM_DELETE_ERROR
	case v1beta1.SERVER_ADDR:
		typesVariableName = types.SERVER_ADDR
	case v1beta1.SERVER_NAME:
		typesVariableName = types.SERVER_NAME
	case v1beta1.SERVER_PORT:
		typesVariableName = types.SERVER_PORT
	case v1beta1.SESSIONID:
		typesVariableName = types.SESSIONID
	case v1beta1.STATUS:
		typesVariableName = types.STATUS
	case v1beta1.STATUS_LINE:
		typesVariableName = types.STATUS_LINE
	case v1beta1.STREAM_INPUT_BODY:
		typesVariableName = types.STREAM_INPUT_BODY
	case v1beta1.STREAM_OUTPUT_BODY:
		typesVariableName = types.STREAM_OUTPUT_BODY
	case v1beta1.TIME:
		typesVariableName = types.TIME
	case v1beta1.TIME_DAY:
		typesVariableName = types.TIME_DAY
	case v1beta1.TIME_EPOCH:
		typesVariableName = types.TIME_EPOCH
	case v1beta1.TIME_HOUR:
		typesVariableName = types.TIME_HOUR
	case v1beta1.TIME_MIN:
		typesVariableName = types.TIME_MIN
	case v1beta1.TIME_MON:
		typesVariableName = types.TIME_MON
	case v1beta1.TIME_SEC:
		typesVariableName = types.TIME_SEC
	case v1beta1.TIME_WDAY:
		typesVariableName = types.TIME_WDAY
	case v1beta1.TIME_YEAR:
		typesVariableName = types.TIME_YEAR
	case v1beta1.UNIQUE_ID:
		typesVariableName = types.UNIQUE_ID
	case v1beta1.UNKNOWN_VAR:
		typesVariableName = types.UNKNOWN_VAR
	case v1beta1.URLENCODED_ERROR:
		typesVariableName = types.URLENCODED_ERROR
	case v1beta1.USERAGENT_IP:
		typesVariableName = types.USERAGENT_IP
	case v1beta1.USERID:
		typesVariableName = types.USERID
	case v1beta1.WEBAPPID:
		typesVariableName = types.WEBAPPID
	case v1beta1.WEBSERVER_ERROR_LOG:
		typesVariableName = types.WEBSERVER_ERROR_LOG
	default: // ignored
	}
	return typesVariableName
}

type VariableReverseMapperImpl struct{}

func (c *VariableReverseMapperImpl) Convert(source types.VariableName) v1beta1.VariableName {
	var v1beta1VariableName v1beta1.VariableName
	switch source {
	case types.ARGS_COMBINED_SIZE:
		v1beta1VariableName = v1beta1.ARGS_COMBINED_SIZE
	case types.AUTH_TYPE:
		v1beta1VariableName = v1beta1.AUTH_TYPE
	case types.DURATION:
		v1beta1VariableName = v1beta1.DURATION
	case types.FILES_COMBINED_SIZE:
		v1beta1VariableName = v1beta1.FILES_COMBINED_SIZE
	case types.FILES_NAMES:
		v1beta1VariableName = v1beta1.FILES_NAMES
	case types.FILES_SIZES:
		v1beta1VariableName = v1beta1.FILES_SIZES
	case types.FILES_TMPNAMES:
		v1beta1VariableName = v1beta1.FILES_TMPNAMES
	case types.FILES_TMP_CONTENT:
		v1beta1VariableName = v1beta1.FILES_TMP_CONTENT
	case types.FULL_REQUEST:
		v1beta1VariableName = v1beta1.FULL_REQUEST
	case types.FULL_REQUEST_LENGTH:
		v1beta1VariableName = v1beta1.FULL_REQUEST_LENGTH
	case types.HIGHEST_SEVERITY:
		v1beta1VariableName = v1beta1.HIGHEST_SEVERITY
	case types.INBOUND_DATA_ERROR:
		v1beta1VariableName = v1beta1.INBOUND_DATA_ERROR
	case types.MATCHED_VAR:
		v1beta1VariableName = v1beta1.MATCHED_VAR
	case types.MATCHED_VAR_NAME:
		v1beta1VariableName = v1beta1.MATCHED_VAR_NAME
	case types.MODSEC_BUILD:
		v1beta1VariableName = v1beta1.MODSEC_BUILD
	case types.MSC_PCRE_ERROR:
		v1beta1VariableName = v1beta1.MSC_PCRE_ERROR
	case types.MSC_PCRE_LIMITS_EXCEEDED:
		v1beta1VariableName = v1beta1.MSC_PCRE_LIMITS_EXCEEDED
	case types.MULTIPART_BOUNDARY_QUOTED:
		v1beta1VariableName = v1beta1.MULTIPART_BOUNDARY_QUOTED
	case types.MULTIPART_BOUNDARY_WHITESPACE:
		v1beta1VariableName = v1beta1.MULTIPART_BOUNDARY_WHITESPACE
	case types.MULTIPART_CRLF_LF_LINES:
		v1beta1VariableName = v1beta1.MULTIPART_CRLF_LF_LINES
	case types.MULTIPART_DATA_AFTER:
		v1beta1VariableName = v1beta1.MULTIPART_DATA_AFTER
	case types.MULTIPART_DATA_BEFORE:
		v1beta1VariableName = v1beta1.MULTIPART_DATA_BEFORE
	case types.MULTIPART_FILENAME:
		v1beta1VariableName = v1beta1.MULTIPART_FILENAME
	case types.MULTIPART_FILE_LIMIT_EXCEEDED:
		v1beta1VariableName = v1beta1.MULTIPART_FILE_LIMIT_EXCEEDED
	case types.MULTIPART_HEADER_FOLDING:
		v1beta1VariableName = v1beta1.MULTIPART_HEADER_FOLDING
	case types.MULTIPART_INVALID_HEADER_FOLDING:
		v1beta1VariableName = v1beta1.MULTIPART_INVALID_HEADER_FOLDING
	case types.MULTIPART_INVALID_PART:
		v1beta1VariableName = v1beta1.MULTIPART_INVALID_PART
	case types.MULTIPART_INVALID_QUOTING:
		v1beta1VariableName = v1beta1.MULTIPART_INVALID_QUOTING
	case types.MULTIPART_LF_LINE:
		v1beta1VariableName = v1beta1.MULTIPART_LF_LINE
	case types.MULTIPART_MISSING_SEMICOLON:
		v1beta1VariableName = v1beta1.MULTIPART_MISSING_SEMICOLON
	case types.MULTIPART_NAME:
		v1beta1VariableName = v1beta1.MULTIPART_NAME
	case types.MULTIPART_SEMICOLON_MISSING:
		v1beta1VariableName = v1beta1.MULTIPART_SEMICOLON_MISSING
	case types.MULTIPART_STRICT_ERROR:
		v1beta1VariableName = v1beta1.MULTIPART_STRICT_ERROR
	case types.MULTIPART_UNMATCHED_BOUNDARY:
		v1beta1VariableName = v1beta1.MULTIPART_UNMATCHED_BOUNDARY
	case types.OUTBOUND_DATA_ERROR:
		v1beta1VariableName = v1beta1.OUTBOUND_DATA_ERROR
	case types.PATH_INFO:
		v1beta1VariableName = v1beta1.PATH_INFO
	case types.PERF_ALL:
		v1beta1VariableName = v1beta1.PERF_ALL
	case types.PERF_COMBINED:
		v1beta1VariableName = v1beta1.PERF_COMBINED
	case types.PERF_GC:
		v1beta1VariableName = v1beta1.PERF_GC
	case types.PERF_LOGGING:
		v1beta1VariableName = v1beta1.PERF_LOGGING
	case types.PERF_PHASE1:
		v1beta1VariableName = v1beta1.PERF_PHASE1
	case types.PERF_PHASE2:
		v1beta1VariableName = v1beta1.PERF_PHASE2
	case types.PERF_PHASE3:
		v1beta1VariableName = v1beta1.PERF_PHASE3
	case types.PERF_PHASE4:
		v1beta1VariableName = v1beta1.PERF_PHASE4
	case types.PERF_PHASE5:
		v1beta1VariableName = v1beta1.PERF_PHASE5
	case types.PERF_SREAD:
		v1beta1VariableName = v1beta1.PERF_SREAD
	case types.PERF_SWRITE:
		v1beta1VariableName = v1beta1.PERF_SWRITE
	case types.QUERY_STRING:
		v1beta1VariableName = v1beta1.QUERY_STRING
	case types.REMOTE_ADDR:
		v1beta1VariableName = v1beta1.REMOTE_ADDR
	case types.REMOTE_HOST:
		v1beta1VariableName = v1beta1.REMOTE_HOST
	case types.REMOTE_PORT:
		v1beta1VariableName = v1beta1.REMOTE_PORT
	case types.REMOTE_USER:
		v1beta1VariableName = v1beta1.REMOTE_USER
	case types.REQBODY_ERROR:
		v1beta1VariableName = v1beta1.REQBODY_ERROR
	case types.REQBODY_ERROR_MSG:
		v1beta1VariableName = v1beta1.REQBODY_ERROR_MSG
	case types.REQBODY_PROCESSOR:
		v1beta1VariableName = v1beta1.REQBODY_PROCESSOR
	case types.REQBODY_PROCESSOR_ERROR:
		v1beta1VariableName = v1beta1.REQBODY_PROCESSOR_ERROR
	case types.REQBODY_PROCESSOR_ERROR_MSG:
		v1beta1VariableName = v1beta1.REQBODY_PROCESSOR_ERROR_MSG
	case types.REQUEST_BASENAME:
		v1beta1VariableName = v1beta1.REQUEST_BASENAME
	case types.REQUEST_BODY:
		v1beta1VariableName = v1beta1.REQUEST_BODY
	case types.REQUEST_BODY_LENGTH:
		v1beta1VariableName = v1beta1.REQUEST_BODY_LENGTH
	case types.REQUEST_FILENAME:
		v1beta1VariableName = v1beta1.REQUEST_FILENAME
	case types.REQUEST_LINE:
		v1beta1VariableName = v1beta1.REQUEST_LINE
	case types.REQUEST_METHOD:
		v1beta1VariableName = v1beta1.REQUEST_METHOD
	case types.REQUEST_PROTOCOL:
		v1beta1VariableName = v1beta1.REQUEST_PROTOCOL
	case types.REQUEST_URI:
		v1beta1VariableName = v1beta1.REQUEST_URI
	case types.REQUEST_URI_RAW:
		v1beta1VariableName = v1beta1.REQUEST_URI_RAW
	case types.RESPONSE_BODY:
		v1beta1VariableName = v1beta1.RESPONSE_BODY
	case types.RESPONSE_CONTENT_LENGTH:
		v1beta1VariableName = v1beta1.RESPONSE_CONTENT_LENGTH
	case types.RESPONSE_CONTENT_TYPE:
		v1beta1VariableName = v1beta1.RESPONSE_CONTENT_TYPE
	case types.RESPONSE_PROTOCOL:
		v1beta1VariableName = v1beta1.RESPONSE_PROTOCOL
	case types.RESPONSE_STATUS:
		v1beta1VariableName = v1beta1.RESPONSE_STATUS
	case types.SCRIPT_BASENAME:
		v1beta1VariableName = v1beta1.SCRIPT_BASENAME
	case types.SCRIPT_FILENAME:
		v1beta1VariableName = v1beta1.SCRIPT_FILENAME
	case types.SCRIPT_GID:
		v1beta1VariableName = v1beta1.SCRIPT_GID
	case types.SCRIPT_GROUPNAME:
		v1beta1VariableName = v1beta1.SCRIPT_GROUPNAME
	case types.SCRIPT_MODE:
		v1beta1VariableName = v1beta1.SCRIPT_MODE
	case types.SCRIPT_UID:
		v1beta1VariableName = v1beta1.SCRIPT_UID
	case types.SCRIPT_USERNAME:
		v1beta1VariableName = v1beta1.SCRIPT_USERNAME
	case types.SDBM_DELETE_ERROR:
		v1beta1VariableName = v1beta1.SDBM_DELETE_ERROR
	case types.SERVER_ADDR:
		v1beta1VariableName = v1beta1.SERVER_ADDR
	case types.SERVER_NAME:
		v1beta1VariableName = v1beta1.SERVER_NAME
	case types.SERVER_PORT:
		v1beta1VariableName = v1beta1.SERVER_PORT
	case types.SESSIONID:
		v1beta1VariableName = v1beta1.SESSIONID
	case types.STATUS:
		v1beta1VariableName = v1beta1.STATUS
	case types.STATUS_LINE:
		v1beta1VariableName = v1beta1.STATUS_LINE
	case types.STREAM_INPUT_BODY:
		v1beta1VariableName = v1beta1.STREAM_INPUT_BODY
	case types.STREAM_OUTPUT_BODY:
		v1beta1VariableName = v1beta1.STREAM_OUTPUT_BODY
	case types.TIME:
		v1beta1VariableName = v1beta1.TIME
	case types.TIME_DAY:
		v1beta1VariableName = v1beta1.TIME_DAY
	case types.TIME_EPOCH:
		v1beta1VariableName = v1beta1.TIME_EPOCH
	case types.TIME_HOUR:
		v1beta1VariableName = v1beta1.TIME_HOUR
	case types.TIME_MIN:
		v1beta1VariableName = v1beta1.TIME_MIN
	case types.TIME_MON:
		v1beta1VariableName = v1beta1.TIME_MON
	case types.TIME_SEC:
		v1beta1VariableName = v1beta1.TIME_SEC
	case types.TIME_WDAY:
		v1beta1VariableName = v1beta1.TIME_WDAY
	case types.TIME_YEAR:
		v1beta1VariableName = v1beta1.TIME_YEAR
	case types.UNIQUE_ID:
		v1beta1VariableName = v1beta1.UNIQUE_ID
	case types.UNKNOWN_VAR:
		v1beta1VariableName = v1beta1.UNKNOWN_VAR
	case types.URLENCODED_ERROR:
		v1beta1VariableName = v1beta1.URLENCODED_ERROR
	case types.USERAGENT_IP:
		v1beta1VariableName = v1beta1.USERAGENT_IP
	case types.USERID:
		v1beta1VariableName = v1beta1.USERID
	case types.WEBAPPID:
		v1beta1VariableName = v1beta1.WEBAPPID
	case types.WEBSERVER_ERROR_LOG:
		v1beta1VariableName = v1beta1.WEBSERVER_ERROR_LOG
	default: // ignored
	}
	return v1beta1VariableName
}
