// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package convert

import (
	types "github.com/coreruleset/crslang/types"
	v1beta1 "github.com/kubewaf-io/kubewaf/api/seclang/v1beta1"
)

type TransformationMapperCSRImpl struct{}

func (c *TransformationMapperCSRImpl) Convert(source types.Transformation) v1beta1.Transformation {
	var v1beta1Transformation v1beta1.Transformation
	switch source {
	case types.Base64Decode:
		v1beta1Transformation = v1beta1.Base64Decode
	case types.Base64DecodeExt:
		v1beta1Transformation = v1beta1.Base64DecodeExt
	case types.Base64Encode:
		v1beta1Transformation = v1beta1.Base64Encode
	case types.CmdLine:
		v1beta1Transformation = v1beta1.CmdLine
	case types.CompressWhitespace:
		v1beta1Transformation = v1beta1.CompressWhitespace
	case types.CssDecode:
		v1beta1Transformation = v1beta1.CssDecode
	case types.EscapeSeqDecode:
		v1beta1Transformation = v1beta1.EscapeSeqDecode
	case types.HexDecode:
		v1beta1Transformation = v1beta1.HexDecode
	case types.HexEncode:
		v1beta1Transformation = v1beta1.HexEncode
	case types.HtmlEntityDecode:
		v1beta1Transformation = v1beta1.HtmlEntityDecode
	case types.JsDecode:
		v1beta1Transformation = v1beta1.JsDecode
	case types.Length:
		v1beta1Transformation = v1beta1.Length
	case types.Lowercase:
		v1beta1Transformation = v1beta1.Lowercase
	case types.Md5:
		v1beta1Transformation = v1beta1.Md5
	case types.None:
		v1beta1Transformation = v1beta1.None
	case types.NormalisePath:
		v1beta1Transformation = v1beta1.NormalisePath
	case types.NormalisePathWin:
		v1beta1Transformation = v1beta1.NormalisePathWin
	case types.ParityEven7bit:
		v1beta1Transformation = v1beta1.ParityEven7bit
	case types.ParityOdd7bit:
		v1beta1Transformation = v1beta1.ParityOdd7bit
	case types.ParityZero7bit:
		v1beta1Transformation = v1beta1.ParityZero7bit
	case types.RemoveComments:
		v1beta1Transformation = v1beta1.RemoveComments
	case types.RemoveCommentsChar:
		v1beta1Transformation = v1beta1.RemoveCommentsChar
	case types.RemoveNulls:
		v1beta1Transformation = v1beta1.RemoveNulls
	case types.RemoveWhitespace:
		v1beta1Transformation = v1beta1.RemoveWhitespace
	case types.ReplaceComments:
		v1beta1Transformation = v1beta1.ReplaceComments
	case types.ReplaceNulls:
		v1beta1Transformation = v1beta1.ReplaceNulls
	case types.Sha1:
		v1beta1Transformation = v1beta1.Sha1
	case types.SqlHexDecode:
		v1beta1Transformation = v1beta1.SqlHexDecode
	case types.Trim:
		v1beta1Transformation = v1beta1.Trim
	case types.TrimLeft:
		v1beta1Transformation = v1beta1.TrimLeft
	case types.TrimRight:
		v1beta1Transformation = v1beta1.TrimRight
	case types.UnknownTransformation:
		v1beta1Transformation = v1beta1.UnknownTransformation
	case types.Uppercase:
		v1beta1Transformation = v1beta1.Uppercase
	case types.UrlDecode:
		v1beta1Transformation = v1beta1.UrlDecode
	case types.UrlDecodeUni:
		v1beta1Transformation = v1beta1.UrlDecodeUni
	case types.UrlEncode:
		v1beta1Transformation = v1beta1.UrlEncode
	case types.Utf8toUnicode:
		v1beta1Transformation = v1beta1.Utf8toUnicode
	default: // ignored
	}
	return v1beta1Transformation
}

type TransformationMapperImpl struct{}

func (c *TransformationMapperImpl) Convert(source v1beta1.Transformation) types.Transformation {
	var typesTransformation types.Transformation
	switch source {
	case v1beta1.Base64Decode:
		typesTransformation = types.Base64Decode
	case v1beta1.Base64DecodeExt:
		typesTransformation = types.Base64DecodeExt
	case v1beta1.Base64Encode:
		typesTransformation = types.Base64Encode
	case v1beta1.CmdLine:
		typesTransformation = types.CmdLine
	case v1beta1.CompressWhitespace:
		typesTransformation = types.CompressWhitespace
	case v1beta1.CssDecode:
		typesTransformation = types.CssDecode
	case v1beta1.EscapeSeqDecode:
		typesTransformation = types.EscapeSeqDecode
	case v1beta1.HexDecode:
		typesTransformation = types.HexDecode
	case v1beta1.HexEncode:
		typesTransformation = types.HexEncode
	case v1beta1.HtmlEntityDecode:
		typesTransformation = types.HtmlEntityDecode
	case v1beta1.JsDecode:
		typesTransformation = types.JsDecode
	case v1beta1.Length:
		typesTransformation = types.Length
	case v1beta1.Lowercase:
		typesTransformation = types.Lowercase
	case v1beta1.Md5:
		typesTransformation = types.Md5
	case v1beta1.None:
		typesTransformation = types.None
	case v1beta1.NormalisePath:
		typesTransformation = types.NormalisePath
	case v1beta1.NormalisePathWin:
		typesTransformation = types.NormalisePathWin
	case v1beta1.ParityEven7bit:
		typesTransformation = types.ParityEven7bit
	case v1beta1.ParityOdd7bit:
		typesTransformation = types.ParityOdd7bit
	case v1beta1.ParityZero7bit:
		typesTransformation = types.ParityZero7bit
	case v1beta1.RemoveComments:
		typesTransformation = types.RemoveComments
	case v1beta1.RemoveCommentsChar:
		typesTransformation = types.RemoveCommentsChar
	case v1beta1.RemoveNulls:
		typesTransformation = types.RemoveNulls
	case v1beta1.RemoveWhitespace:
		typesTransformation = types.RemoveWhitespace
	case v1beta1.ReplaceComments:
		typesTransformation = types.ReplaceComments
	case v1beta1.ReplaceNulls:
		typesTransformation = types.ReplaceNulls
	case v1beta1.Sha1:
		typesTransformation = types.Sha1
	case v1beta1.SqlHexDecode:
		typesTransformation = types.SqlHexDecode
	case v1beta1.Trim:
		typesTransformation = types.Trim
	case v1beta1.TrimLeft:
		typesTransformation = types.TrimLeft
	case v1beta1.TrimRight:
		typesTransformation = types.TrimRight
	case v1beta1.UnknownTransformation:
		typesTransformation = types.UnknownTransformation
	case v1beta1.Uppercase:
		typesTransformation = types.Uppercase
	case v1beta1.UrlDecode:
		typesTransformation = types.UrlDecode
	case v1beta1.UrlDecodeUni:
		typesTransformation = types.UrlDecodeUni
	case v1beta1.UrlEncode:
		typesTransformation = types.UrlEncode
	case v1beta1.Utf8toUnicode:
		typesTransformation = types.Utf8toUnicode
	default: // ignored
	}
	return typesTransformation
}
