// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package convert

import (
	types "github.com/coreruleset/crslang/types"
	v1beta1 "github.com/kubewaf-io/kubewaf/api/seclang/v1beta1"
)

type DataActionTypeMapperImpl struct{}

func (c *DataActionTypeMapperImpl) Convert(source v1beta1.DataActionType) types.DataAction {
	var typesDataAction types.DataAction
	switch source {
	case v1beta1.Status:
		typesDataAction = types.Status
	case v1beta1.XLMNS:
		typesDataAction = types.XLMNS
	default:
		typesDataAction = types.DataUnknown
	}
	return typesDataAction
}

type DisruptiveActionMapperImpl struct{}

func (c *DisruptiveActionMapperImpl) Convert(source v1beta1.DisruptiveActionType) types.DisruptiveAction {
	var typesDisruptiveAction types.DisruptiveAction
	switch source {
	case v1beta1.Allow:
		typesDisruptiveAction = types.Allow
	case v1beta1.Block:
		typesDisruptiveAction = types.Block
	case v1beta1.Deny:
		typesDisruptiveAction = types.Deny
	case v1beta1.Drop:
		typesDisruptiveAction = types.Drop
	case v1beta1.Pass:
		typesDisruptiveAction = types.Pass
	case v1beta1.Pause:
		typesDisruptiveAction = types.Pause
	case v1beta1.Proxy:
		typesDisruptiveAction = types.Proxy
	case v1beta1.Redirect:
		typesDisruptiveAction = types.Redirect
	default:
		typesDisruptiveAction = types.Unknown
	}
	return typesDisruptiveAction
}

type FlowActionTypeMapperImpl struct{}

func (c *FlowActionTypeMapperImpl) Convert(source v1beta1.FlowActionType) types.FlowAction {
	var typesFlowAction types.FlowAction
	switch source {
	case v1beta1.Chain:
		typesFlowAction = types.Chain
	case v1beta1.FlowUnknown:
		typesFlowAction = types.FlowUnknown
	case v1beta1.Skip:
		typesFlowAction = types.Skip
	case v1beta1.SkipAfter:
		typesFlowAction = types.SkipAfter
	default:
		typesFlowAction = types.FlowUnknown
	}
	return typesFlowAction
}

type FlowActionTypeReverseMapperImpl struct{}

func (c *FlowActionTypeReverseMapperImpl) Convert(source types.FlowAction) v1beta1.FlowActionType {
	var v1beta1FlowActionType v1beta1.FlowActionType
	switch source {
	case types.Chain:
		v1beta1FlowActionType = v1beta1.Chain
	case types.FlowUnknown:
		v1beta1FlowActionType = v1beta1.FlowUnknown
	case types.Skip:
		v1beta1FlowActionType = v1beta1.Skip
	case types.SkipAfter:
		v1beta1FlowActionType = v1beta1.SkipAfter
	default: // ignored
	}
	return v1beta1FlowActionType
}

type NonDisruptiveActionTypeMapperImpl struct{}

func (c *NonDisruptiveActionTypeMapperImpl) Convert(source v1beta1.NonDisruptiveActionType) types.NonDisruptiveAction {
	var typesNonDisruptiveAction types.NonDisruptiveAction
	switch source {
	case v1beta1.Append:
		typesNonDisruptiveAction = types.Append
	case v1beta1.AuditLog:
		typesNonDisruptiveAction = types.AuditLog
	case v1beta1.Capture:
		typesNonDisruptiveAction = types.Capture
	case v1beta1.Ctl:
		typesNonDisruptiveAction = types.Ctl
	case v1beta1.DeprecateVar:
		typesNonDisruptiveAction = types.DeprecateVar
	case v1beta1.Exec:
		typesNonDisruptiveAction = types.Exec
	case v1beta1.ExpireVar:
		typesNonDisruptiveAction = types.ExpireVar
	case v1beta1.InitCol:
		typesNonDisruptiveAction = types.InitCol
	case v1beta1.Log:
		typesNonDisruptiveAction = types.Log
	case v1beta1.LogData:
		typesNonDisruptiveAction = types.LogData
	case v1beta1.MultiMatch:
		typesNonDisruptiveAction = types.MultiMatch
	case v1beta1.NoAuditLog:
		typesNonDisruptiveAction = types.NoAuditLog
	case v1beta1.NoLog:
		typesNonDisruptiveAction = types.NoLog
	case v1beta1.SanitiseArg:
		typesNonDisruptiveAction = types.SanitiseArg
	case v1beta1.SanitiseMatched:
		typesNonDisruptiveAction = types.SanitiseMatched
	case v1beta1.SanitiseMatchedBytes:
		typesNonDisruptiveAction = types.SanitiseMatchedBytes
	case v1beta1.SanitiseRequestHeader:
		typesNonDisruptiveAction = types.SanitiseRequestHeader
	case v1beta1.SanitiseResponseHeader:
		typesNonDisruptiveAction = types.SanitiseResponseHeader
	case v1beta1.SetEnv:
		typesNonDisruptiveAction = types.SetEnv
	case v1beta1.SetRsc:
		typesNonDisruptiveAction = types.SetRsc
	case v1beta1.SetSid:
		typesNonDisruptiveAction = types.SetSid
	case v1beta1.SetUid:
		typesNonDisruptiveAction = types.SetUid
	case v1beta1.SetVar:
		typesNonDisruptiveAction = types.SetVar
	default:
		typesNonDisruptiveAction = types.NonDisruptiveUnknown
	}
	return typesNonDisruptiveAction
}
