---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - seclan.kubewaf.io
  resources:
  - secrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - seclan.kubewaf.io
  resources:
  - secrules/finalizers
  verbs:
  - update
- apiGroups:
  - seclan.kubewaf.io
  resources:
  - secrules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - seclang.kubewaf.io
  resources:
  - rulesets
  - secrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - seclang.kubewaf.io
  resources:
  - secactions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - seclang.kubewaf.io
  resources:
  - secactions/finalizers
  verbs:
  - update
- apiGroups:
  - seclang.kubewaf.io
  resources:
  - secactions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - seclang.kubewaf.io
  resources:
  - secrules/status
  verbs:
  - patch
  - update
- apiGroups:
  - waf.kubewaf.io
  resources:
  - rulesets
  - wafenvoygateways
  - wafinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - waf.kubewaf.io
  resources:
  - rulesets/finalizers
  - wafenvoygateways/finalizers
  - wafinstances/finalizers
  verbs:
  - update
- apiGroups:
  - waf.kubewaf.io
  resources:
  - rulesets/status
  - wafenvoygateways/status
  - wafinstances/status
  verbs:
  - get
  - patch
  - update
