# syntax=docker/dockerfile:1
FROM scratch
LABEL org.opencontainers.image.title="challenge-proxy-wasm"
LABEL org.opencontainers.image.description="Lightweight Proxy-WASM browser challenge (PoW) filter"
LABEL org.opencontainers.image.source="https://github.com/chifu/challange-proxy-wasm"
COPY build/main.wasm /plugin.wasm
