apiVersion: waf.kubewaf.io/v1beta1
kind: RuleSet
metadata:
  name: ruleset-sample
spec:
  ruleRefs:
    - kind: "SecRule"
      group: "seclang.kubewaf.io"
      version: "v1beta1"
      selector:
        matchLabels:
          test: "true"
