apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-905-COMMON-EXCEPTIONS.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "905100"
    seclang.kubewaf.io/order: "905100"
    seclang.kubewaf.io/phase: "1"
  name: crs-905100
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - operator:
      name: strEq
      value: GET /
    transformations:
    - none
    variables:
    - name: REQUEST_LINE
  - actions:

      non-disruptive:
      - nonDisruptiveActionType: ctl
        value: ruleRemoveByTag=OWASP_CRS
      - nonDisruptiveActionType: ctl
        value: auditEngine=Off
    operator:
      name: ipMatch
      value: 127.0.0.1,::1
    transformations:
    - none
    variables:
    - name: REMOTE_ADDR
  metadata:
    id: 905100
    phase: "1"
  order: 905100
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-905-COMMON-EXCEPTIONS.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "905110"
    seclang.kubewaf.io/order: "905110"
    seclang.kubewaf.io/phase: "1"
  name: crs-905110
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - operator:
      name: ipMatch
      value: 127.0.0.1,::1
    transformations:
    - none
    variables:
    - name: REMOTE_ADDR
  - actions:

      non-disruptive:
      - nonDisruptiveActionType: ctl
        value: ruleRemoveByTag=OWASP_CRS
      - nonDisruptiveActionType: ctl
        value: auditEngine=Off
    collections:
    - arguments:
      - User-Agent
      name: REQUEST_HEADERS
    operator:
      name: endsWith
      value: (internal dummy connection)
    transformations:
    - none
  metadata:
    comment: |+
      Exception for Apache internal dummy connection

    id: 905110
    phase: "1"
  order: 905110
