apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-922-MULTIPART-ATTACK.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "922100"
    seclang.kubewaf.io/order: "922100"
    seclang.kubewaf.io/phase: "2"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.capec.1000.255.153: "true"
    seclang.kubewaf.io/tag.language-multi: "true"
    seclang.kubewaf.io/tag.paranoia-level.1: "true"
    seclang.kubewaf.io/tag.platform-multi: "true"
  name: crs-922100
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: logdata
      value: 'Matched Data: %{ARGS._charset_}'
    - nonDisruptiveActionType: setvar
      value: TX.922100_charset=|%{ARGS._charset_}|
  match:
  - collections:
    - arguments:
      - _charset_
      count: true
      name: MULTIPART_PART_HEADERS
    operator:
      name: eq
      negate: true
      value: "0"
    transformations:
    - none
  - actions:

      non-disruptive:
      - nonDisruptiveActionType: setvar
        value: TX.inbound_anomaly_score_pl1=+%{tx.critical_anomaly_score}
    collections:
    - arguments:
      - 922100_CHARSET
      name: TX
    operator:
      name: within
      negate: true
      value: '%{tx.allowed_request_content_type_charset}'
    transformations:
    - lowercase
  metadata:
    id: 922100
    message: Multipart content type global _charset_ definition is not allowed by
      policy
    phase: "2"
    severity: CRITICAL
    tags:
    - application-multi
    - language-multi
    - platform-multi
    - paranoia-level/1
    - capec/1000/255/153
  order: 922100
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-922-MULTIPART-ATTACK.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "922140"
    seclang.kubewaf.io/order: "922140"
    seclang.kubewaf.io/phase: "2"
  name: crs-922140
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    non-disruptive:
    - nonDisruptiveActionType: nolog
    - nonDisruptiveActionType: setvar
      value: TX.multipart_headers_content_counter=0
  match:
  - collections:
    - count: true
      name: MULTIPART_PART_HEADERS
    operator:
      name: gt
      value: "0"
    transformations:
    - none
  metadata:
    comment: |+
      Only allow specific charsets same as Rule 920600
      Note: this is in phase:2 because these are headers that come in the body

      How do these rules work:
      * rule 922140 sets the multipart counter TX variable to 0
        note that this is why does not matter if more parts have the same name - see rule's test
      * rule 922150 collects all multipart headers' 'Content-Type' value
        eg. 'text/plain; charset=utf-8'
      * rule 922110 checks all the collected headers' content type and charset

    id: 922140
    phase: "2"
  order: 922140
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-922-MULTIPART-ATTACK.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "922150"
    seclang.kubewaf.io/order: "922150"
    seclang.kubewaf.io/phase: "2"
  name: crs-922150
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    non-disruptive:
    - nonDisruptiveActionType: capture
    - nonDisruptiveActionType: nolog
    - nonDisruptiveActionType: setvar
      value: TX.multipart_headers_content_types_%{tx.multipart_headers_content_counter}=%{tx.1}
    - nonDisruptiveActionType: setvar
      value: TX.multipart_headers_content_counter=+1
  match:
  - collections:
    - name: MULTIPART_PART_HEADERS
    operator:
      name: rx
      value: ^content-type\s*:\s*(.*)$
    transformations:
    - none
    - lowercase
  metadata:
    id: 922150
    phase: "2"
  order: 922150
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-922-MULTIPART-ATTACK.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "922110"
    seclang.kubewaf.io/order: "922110"
    seclang.kubewaf.io/phase: "2"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.attack-protocol: "true"
    seclang.kubewaf.io/tag.capec.272.220: "true"
    seclang.kubewaf.io/tag.language-multi: "true"
    seclang.kubewaf.io/tag.paranoia-level.1: "true"
    seclang.kubewaf.io/tag.platform-multi: "true"
  name: crs-922110
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: capture
    - nonDisruptiveActionType: logdata
      value: 'Matched Data: %{MATCHED_VAR} found within Content-Type multipart form'
    - nonDisruptiveActionType: setvar
      value: TX.inbound_anomaly_score_pl1=+%{tx.critical_anomaly_score}
  match:
  - collections:
    - arguments:
      - /MULTIPART_HEADERS_CONTENT_TYPES_*/
      name: TX
    operator:
      name: rx
      negate: true
      value: ^(?:(?:\*|[^!\"\(\),/:-\?\[-\]\{\}]+)/(?:\*|[^!\"\(\),/:-\?\[-\]\{\}]+)|\*)(?:[\s\x0b]*;[\s\x0b]*(?:charset[\s\x0b]*=[\s\x0b]*\"?(?:iso-8859-15?|utf-8|windows-1252)\b\"?|(?:[^\s\x0b-\"\(\),/:-\?\[-\]c\{\}]|c(?:[^!\"\(\),/:-\?\[-\]h\{\}]|h(?:[^!\"\(\),/:-\?\[-\]a\{\}]|a(?:[^!\"\(\),/:-\?\[-\]r\{\}]|r(?:[^!\"\(\),/:-\?\[-\]s\{\}]|s(?:[^!\"\(\),/:-\?\[-\]e\{\}]|e[^!\"\(\),/:-\?\[-\]t\{\}]))))))[^!\"\(\),/:-\?\[-\]\{\}]*[\s\x0b]*=[\s\x0b]*[^!\(\),/:-\?\[-\]\{\}]+);?)*(?:[\s\x0b]*,[\s\x0b]*(?:(?:\*|[^!\"\(\),/:-\?\[-\]\{\}]+)/(?:\*|[^!\"\(\),/:-\?\[-\]\{\}]+)|\*)(?:[\s\x0b]*;[\s\x0b]*(?:charset[\s\x0b]*=[\s\x0b]*\"?(?:iso-8859-15?|utf-8|windows-1252)\b\"?|(?:[^\s\x0b-\"\(\),/:-\?\[-\]c\{\}]|c(?:[^!\"\(\),/:-\?\[-\]h\{\}]|h(?:[^!\"\(\),/:-\?\[-\]a\{\}]|a(?:[^!\"\(\),/:-\?\[-\]r\{\}]|r(?:[^!\"\(\),/:-\?\[-\]s\{\}]|s(?:[^!\"\(\),/:-\?\[-\]e\{\}]|e[^!\"\(\),/:-\?\[-\]t\{\}]))))))[^!\"\(\),/:-\?\[-\]\{\}]*[\s\x0b]*=[\s\x0b]*[^!\(\),/:-\?\[-\]\{\}]+);?)*)*$
    transformations:
    - none
    - lowercase
  metadata:
    comment: |
      Regular expression generated from regex-assembly/922110.ra.
      To update the regular expression run the following shell script
      (consult https://coreruleset.org/docs/development/regex_assembly/ for details):
        crs-toolchain regex update 922110
    id: 922110
    message: 'Illegal MIME Multipart Header content-type: charset parameter'
    phase: "2"
    severity: CRITICAL
    tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-protocol
    - paranoia-level/1
    - capec/272/220
  order: 922110
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-922-MULTIPART-ATTACK.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "922120"
    seclang.kubewaf.io/order: "922120"
    seclang.kubewaf.io/phase: "2"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.attack-deprecated-header: "true"
    seclang.kubewaf.io/tag.capec.272.220: "true"
    seclang.kubewaf.io/tag.language-multi: "true"
    seclang.kubewaf.io/tag.paranoia-level.1: "true"
    seclang.kubewaf.io/tag.platform-multi: "true"
  name: crs-922120
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: capture
    - nonDisruptiveActionType: logdata
      value: 'Matched Data: %{TX.0}'
    - nonDisruptiveActionType: setvar
      value: TX.inbound_anomaly_score_pl1=+%{tx.critical_anomaly_score}
  match:
  - collections:
    - name: MULTIPART_PART_HEADERS
    operator:
      name: rx
      value: content-transfer-encoding:(.*)
    transformations:
    - none
    - lowercase
  metadata:
    comment: |
      Content-Transfer-Encoding was deprecated by rfc7578 in 2015 and should not be used (see: https://www.rfc-editor.org/rfc/rfc7578#section-4.7)
      Note: this is in phase:2 because these are headers that come in the body
    id: 922120
    message: Content-Transfer-Encoding was deprecated by rfc7578 in 2015 and should
      not be used
    phase: "2"
    severity: CRITICAL
    tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-deprecated-header
    - paranoia-level/1
    - capec/272/220
  order: 922120
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-922-MULTIPART-ATTACK.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "922130"
    seclang.kubewaf.io/order: "922130"
    seclang.kubewaf.io/phase: "2"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.capec.272.220: "true"
    seclang.kubewaf.io/tag.language-multi: "true"
    seclang.kubewaf.io/tag.paranoia-level.1: "true"
    seclang.kubewaf.io/tag.platform-multi: "true"
  name: crs-922130
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: capture
    - nonDisruptiveActionType: logdata
      value: 'Matched Data: %{TX.0}'
    - nonDisruptiveActionType: setvar
      value: TX.inbound_anomaly_score_pl1=+%{tx.critical_anomaly_score}
  match:
  - collections:
    - name: MULTIPART_PART_HEADERS
    operator:
      name: rx
      value: '[^\x21-\x7E][\x21-\x39\x3B-\x7E]*:'
    transformations:
    - none
    - lowercase
  metadata:
    comment: |
      Multipart header names can't contain any characters outside of range 33 and 126,
      excluding 58 (':') which is the separator.
      RFC 2045 refers RFC 822 about the header syntax.
      Note: this is in phase:2 because these are headers that come in the body
    id: 922130
    message: Multipart header contains characters outside of valid range
    phase: "2"
    severity: CRITICAL
    tags:
    - application-multi
    - language-multi
    - platform-multi
    - paranoia-level/1
    - capec/272/220
  order: 922130
