apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-952-DATA-LEAKAGES-JAVA.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "952010"
    seclang.kubewaf.io/order: "952010"
    seclang.kubewaf.io/phase: "4"
    seclang.kubewaf.io/tag.owasp_crs.data-leakages-java: "true"
  name: crs-952010
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-952-DATA-LEAKAGES-JAVA
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - Content-Encoding
      name: RESPONSE_HEADERS
    operator:
      name: pm
      value: gzip compress deflate br zstd
  metadata:
    id: 952010
    phase: "4"
    tags:
    - OWASP_CRS/DATA-LEAKAGES-JAVA
  order: 952010
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-952-DATA-LEAKAGES-JAVA.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "952011"
    seclang.kubewaf.io/order: "952011"
    seclang.kubewaf.io/phase: "3"
  name: crs-952011
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-952-DATA-LEAKAGES-JAVA
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "1"
  metadata:
    id: 952011
    phase: "3"
  order: 952011
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-952-DATA-LEAKAGES-JAVA.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "952012"
    seclang.kubewaf.io/order: "952012"
    seclang.kubewaf.io/phase: "4"
  name: crs-952012
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-952-DATA-LEAKAGES-JAVA
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "1"
  metadata:
    id: 952012
    phase: "4"
  order: 952012
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-952-DATA-LEAKAGES-JAVA.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "952110"
    seclang.kubewaf.io/order: "952110"
    seclang.kubewaf.io/phase: "4"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.attack-disclosure: "true"
    seclang.kubewaf.io/tag.capec.1000.118.116: "true"
    seclang.kubewaf.io/tag.language-java: "true"
    seclang.kubewaf.io/tag.owasp_crs.data-leakages-java: "true"
    seclang.kubewaf.io/tag.paranoia-level.1: "true"
    seclang.kubewaf.io/tag.platform-multi: "true"
  name: crs-952110
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: capture
    - nonDisruptiveActionType: logdata
      value: 'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}'
    - nonDisruptiveActionType: setvar
      value: TX.outbound_anomaly_score_pl1=+%{tx.error_anomaly_score}
  match:
  - operator:
      name: rx
      value: (?i)\b(?:java[\.a-z]+E(?:xception|rror)|(?:org|com)\.[\.a-z]+Exception|Exception
        in thread \"[^\"]*\"|at[\s\x0b]+(?:ja(?:vax?|karta)|org|com))\b
    transformations:
    - none
    variables:
    - name: RESPONSE_BODY
  metadata:
    id: 952110
    message: Java Errors
    phase: "4"
    severity: ERROR
    tags:
    - application-multi
    - language-java
    - platform-multi
    - attack-disclosure
    - paranoia-level/1
    - OWASP_CRS/DATA-LEAKAGES-JAVA
    - capec/1000/118/116
  order: 952110
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-952-DATA-LEAKAGES-JAVA.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "952013"
    seclang.kubewaf.io/order: "952013"
    seclang.kubewaf.io/phase: "3"
  name: crs-952013
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-952-DATA-LEAKAGES-JAVA
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "2"
  metadata:
    id: 952013
    phase: "3"
  order: 952013
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-952-DATA-LEAKAGES-JAVA.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "952014"
    seclang.kubewaf.io/order: "952014"
    seclang.kubewaf.io/phase: "4"
  name: crs-952014
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-952-DATA-LEAKAGES-JAVA
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "2"
  metadata:
    id: 952014
    phase: "4"
  order: 952014
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-952-DATA-LEAKAGES-JAVA.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "952015"
    seclang.kubewaf.io/order: "952015"
    seclang.kubewaf.io/phase: "3"
  name: crs-952015
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-952-DATA-LEAKAGES-JAVA
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "3"
  metadata:
    comment: |+
      -= Paranoia Level 2 =- (apply only when tx.detection_paranoia_level is sufficiently high: 2 or higher)

    id: 952015
    phase: "3"
  order: 952015
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-952-DATA-LEAKAGES-JAVA.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "952016"
    seclang.kubewaf.io/order: "952016"
    seclang.kubewaf.io/phase: "4"
  name: crs-952016
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-952-DATA-LEAKAGES-JAVA
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "3"
  metadata:
    id: 952016
    phase: "4"
  order: 952016
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-952-DATA-LEAKAGES-JAVA.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "952017"
    seclang.kubewaf.io/order: "952017"
    seclang.kubewaf.io/phase: "3"
  name: crs-952017
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-952-DATA-LEAKAGES-JAVA
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "4"
  metadata:
    comment: |+
      -= Paranoia Level 3 =- (apply only when tx.detection_paranoia_level is sufficiently high: 3 or higher)

    id: 952017
    phase: "3"
  order: 952017
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-952-DATA-LEAKAGES-JAVA.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "952018"
    seclang.kubewaf.io/order: "952018"
    seclang.kubewaf.io/phase: "4"
  name: crs-952018
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-952-DATA-LEAKAGES-JAVA
    non-disruptive:
    - nonDisruptiveActionType: nolog
  markerAfter: END-RESPONSE-952-DATA-LEAKAGES-JAVA
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "4"
  metadata:
    id: 952018
    phase: "4"
  order: 952018
