apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-950-DATA-LEAKAGES.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "950021"
    seclang.kubewaf.io/order: "950021"
    seclang.kubewaf.io/phase: "3"
    seclang.kubewaf.io/tag.owasp_crs.data-leakages: "true"
  name: crs-950021
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-959-BLOCKING-EVALUATION
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - crs_skip_response_analysis
      name: TX
    operator:
      name: eq
      value: "1"
  metadata:
    id: 950021
    phase: "3"
    tags:
    - OWASP_CRS/DATA-LEAKAGES
  order: 950021
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-950-DATA-LEAKAGES.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "950010"
    seclang.kubewaf.io/order: "950010"
    seclang.kubewaf.io/phase: "4"
    seclang.kubewaf.io/tag.owasp_crs.data-leakages: "true"
  name: crs-950010
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-950-DATA-LEAKAGES
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - Content-Encoding
      name: RESPONSE_HEADERS
    operator:
      name: pm
      value: gzip compress deflate br zstd
  metadata:
    comment: |
      Skip all rules if RESPONSE_BODY is compressed.
    id: 950010
    phase: "4"
    tags:
    - OWASP_CRS/DATA-LEAKAGES
  order: 950010
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-950-DATA-LEAKAGES.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "950011"
    seclang.kubewaf.io/order: "950011"
    seclang.kubewaf.io/phase: "3"
  name: crs-950011
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-950-DATA-LEAKAGES
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "1"
  metadata:
    id: 950011
    phase: "3"
  order: 950011
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-950-DATA-LEAKAGES.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "950012"
    seclang.kubewaf.io/order: "950012"
    seclang.kubewaf.io/phase: "4"
  name: crs-950012
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-950-DATA-LEAKAGES
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "1"
  metadata:
    id: 950012
    phase: "4"
  order: 950012
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-950-DATA-LEAKAGES.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "950130"
    seclang.kubewaf.io/order: "950130"
    seclang.kubewaf.io/phase: "4"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.attack-disclosure: "true"
    seclang.kubewaf.io/tag.capec.1000.118.116.54.127: "true"
    seclang.kubewaf.io/tag.language-multi: "true"
    seclang.kubewaf.io/tag.owasp_crs.data-leakages: "true"
    seclang.kubewaf.io/tag.paranoia-level.1: "true"
    seclang.kubewaf.io/tag.platform-multi: "true"
  name: crs-950130
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: capture
    - nonDisruptiveActionType: logdata
      value: 'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}'
    - nonDisruptiveActionType: setvar
      value: TX.outbound_anomaly_score_pl1=+%{tx.error_anomaly_score}
  match:
  - operator:
      name: rx
      value: (?:<(?:TITLE>Index of.*?<H|title>Index of.*?<h)1>Index of|>\[To Parent
        Directory\]</[Aa]><br>)
    transformations:
    - none
    variables:
    - name: RESPONSE_BODY
  metadata:
    id: 950130
    message: Directory Listing
    phase: "4"
    severity: ERROR
    tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-disclosure
    - paranoia-level/1
    - OWASP_CRS/DATA-LEAKAGES
    - capec/1000/118/116/54/127
  order: 950130
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-950-DATA-LEAKAGES.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "950140"
    seclang.kubewaf.io/order: "950140"
    seclang.kubewaf.io/phase: "4"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.attack-disclosure: "true"
    seclang.kubewaf.io/tag.capec.1000.118.116: "true"
    seclang.kubewaf.io/tag.language-multi: "true"
    seclang.kubewaf.io/tag.owasp_crs.data-leakages: "true"
    seclang.kubewaf.io/tag.paranoia-level.1: "true"
    seclang.kubewaf.io/tag.platform-multi: "true"
  name: crs-950140
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: capture
    - nonDisruptiveActionType: logdata
      value: 'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}'
    - nonDisruptiveActionType: setvar
      value: TX.outbound_anomaly_score_pl1=+%{tx.error_anomaly_score}
  match:
  - operator:
      name: rx
      value: ^#\!\s?/
    transformations:
    - none
    variables:
    - name: RESPONSE_BODY
  metadata:
    comment: |
      -=[ CGI Source Code Leakage ]=-

      A CGI script begins normally with #! and the interpreter,
      for example:

      #!/usr/bin/perl
      #!/usr/bin/python
      #!/usr/bin/ruby

      If the CGI script processors or MIME type handlers are misconfigured,
      the script's source code could be erroneously returned to the client.
    id: 950140
    message: CGI source code leakage
    phase: "4"
    severity: ERROR
    tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-disclosure
    - paranoia-level/1
    - OWASP_CRS/DATA-LEAKAGES
    - capec/1000/118/116
  order: 950140
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-950-DATA-LEAKAGES.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "950150"
    seclang.kubewaf.io/order: "950150"
    seclang.kubewaf.io/phase: "4"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.attack-disclosure: "true"
    seclang.kubewaf.io/tag.capec.1000.118.116.54.127: "true"
    seclang.kubewaf.io/tag.language-aspnet: "true"
    seclang.kubewaf.io/tag.owasp_crs.data-leakages: "true"
    seclang.kubewaf.io/tag.paranoia-level.1: "true"
    seclang.kubewaf.io/tag.platform-multi: "true"
  name: crs-950150
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: capture
    - nonDisruptiveActionType: logdata
      value: 'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}'
    - nonDisruptiveActionType: setvar
      value: TX.outbound_anomaly_score_pl1=+%{tx.error_anomaly_score}
  match:
  - operator:
      name: pmFromFile
      value: asp-dotnet-errors.data
    transformations:
    - none
    variables:
    - name: RESPONSE_BODY
  metadata:
    comment: |+
      -=[ ASP.NET Errors ]=-

    id: 950150
    message: ASP.NET exception leakage
    phase: "4"
    severity: ERROR
    tags:
    - application-multi
    - language-aspnet
    - platform-multi
    - attack-disclosure
    - paranoia-level/1
    - OWASP_CRS/DATA-LEAKAGES
    - capec/1000/118/116/54/127
  order: 950150
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-950-DATA-LEAKAGES.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "950013"
    seclang.kubewaf.io/order: "950013"
    seclang.kubewaf.io/phase: "3"
  name: crs-950013
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-950-DATA-LEAKAGES
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "2"
  metadata:
    id: 950013
    phase: "3"
  order: 950013
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-950-DATA-LEAKAGES.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "950014"
    seclang.kubewaf.io/order: "950014"
    seclang.kubewaf.io/phase: "4"
  name: crs-950014
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-950-DATA-LEAKAGES
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "2"
  metadata:
    id: 950014
    phase: "4"
  order: 950014
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-950-DATA-LEAKAGES.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "950100"
    seclang.kubewaf.io/order: "950100"
    seclang.kubewaf.io/phase: "3"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.attack-disclosure: "true"
    seclang.kubewaf.io/tag.capec.1000.152: "true"
    seclang.kubewaf.io/tag.language-multi: "true"
    seclang.kubewaf.io/tag.owasp_crs.data-leakages: "true"
    seclang.kubewaf.io/tag.paranoia-level.2: "true"
    seclang.kubewaf.io/tag.platform-multi: "true"
  name: crs-950100
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: capture
    - nonDisruptiveActionType: logdata
      value: 'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}'
    - nonDisruptiveActionType: setvar
      value: TX.outbound_anomaly_score_pl2=+%{tx.error_anomaly_score}
  match:
  - operator:
      name: rx
      value: ^5\d{2}$
    transformations:
    - none
    variables:
    - name: RESPONSE_STATUS
  metadata:
    id: 950100
    message: The Application Returned a 500-Level Status Code
    phase: "3"
    severity: ERROR
    tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-disclosure
    - paranoia-level/2
    - OWASP_CRS/DATA-LEAKAGES
    - capec/1000/152
  order: 950100
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-950-DATA-LEAKAGES.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "950015"
    seclang.kubewaf.io/order: "950015"
    seclang.kubewaf.io/phase: "3"
  name: crs-950015
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-950-DATA-LEAKAGES
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "3"
  metadata:
    id: 950015
    phase: "3"
  order: 950015
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-950-DATA-LEAKAGES.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "950016"
    seclang.kubewaf.io/order: "950016"
    seclang.kubewaf.io/phase: "4"
  name: crs-950016
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-950-DATA-LEAKAGES
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "3"
  metadata:
    id: 950016
    phase: "4"
  order: 950016
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-950-DATA-LEAKAGES.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "950017"
    seclang.kubewaf.io/order: "950017"
    seclang.kubewaf.io/phase: "3"
  name: crs-950017
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-950-DATA-LEAKAGES
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "4"
  metadata:
    comment: |+
      -= Paranoia Level 3 =- (apply only when tx.detection_paranoia_level is sufficiently high: 3 or higher)

    id: 950017
    phase: "3"
  order: 950017
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-950-DATA-LEAKAGES.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "950018"
    seclang.kubewaf.io/order: "950018"
    seclang.kubewaf.io/phase: "4"
  name: crs-950018
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-950-DATA-LEAKAGES
    non-disruptive:
    - nonDisruptiveActionType: nolog
  markerAfter: END-RESPONSE-950-DATA-LEAKAGES
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "4"
  metadata:
    id: 950018
    phase: "4"
  order: 950018
