apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-911-METHOD-ENFORCEMENT.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "911011"
    seclang.kubewaf.io/order: "911011"
    seclang.kubewaf.io/phase: "1"
  name: crs-911011
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REQUEST-911-METHOD-ENFORCEMENT
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "1"
  metadata:
    id: 911011
    phase: "1"
  order: 911011
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-911-METHOD-ENFORCEMENT.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "911012"
    seclang.kubewaf.io/order: "911012"
    seclang.kubewaf.io/phase: "2"
  name: crs-911012
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REQUEST-911-METHOD-ENFORCEMENT
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "1"
  metadata:
    id: 911012
    phase: "2"
  order: 911012
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-911-METHOD-ENFORCEMENT.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "911100"
    seclang.kubewaf.io/order: "911100"
    seclang.kubewaf.io/phase: "1"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.attack-generic: "true"
    seclang.kubewaf.io/tag.capec.1000.210.272.220.274: "true"
    seclang.kubewaf.io/tag.language-multi: "true"
    seclang.kubewaf.io/tag.owasp_crs.method-enforcement: "true"
    seclang.kubewaf.io/tag.paranoia-level.1: "true"
    seclang.kubewaf.io/tag.platform-multi: "true"
  name: crs-911100
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: logdata
      value: '%{MATCHED_VAR}'
    - nonDisruptiveActionType: setvar
      value: TX.inbound_anomaly_score_pl1=+%{tx.critical_anomaly_score}
  match:
  - operator:
      name: within
      negate: true
      value: '%{tx.allowed_methods}'
    variables:
    - name: REQUEST_METHOD
  metadata:
    id: 911100
    message: Method is not allowed by policy
    phase: "1"
    severity: CRITICAL
    tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-generic
    - paranoia-level/1
    - OWASP_CRS/METHOD-ENFORCEMENT
    - capec/1000/210/272/220/274
  order: 911100
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-911-METHOD-ENFORCEMENT.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "911013"
    seclang.kubewaf.io/order: "911013"
    seclang.kubewaf.io/phase: "1"
  name: crs-911013
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REQUEST-911-METHOD-ENFORCEMENT
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "2"
  metadata:
    id: 911013
    phase: "1"
  order: 911013
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-911-METHOD-ENFORCEMENT.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "911014"
    seclang.kubewaf.io/order: "911014"
    seclang.kubewaf.io/phase: "2"
  name: crs-911014
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REQUEST-911-METHOD-ENFORCEMENT
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "2"
  metadata:
    id: 911014
    phase: "2"
  order: 911014
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-911-METHOD-ENFORCEMENT.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "911015"
    seclang.kubewaf.io/order: "911015"
    seclang.kubewaf.io/phase: "1"
  name: crs-911015
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REQUEST-911-METHOD-ENFORCEMENT
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "3"
  metadata:
    comment: |+
      -= Paranoia Level 2 =- (apply only when tx.detection_paranoia_level is sufficiently high: 2 or higher)

    id: 911015
    phase: "1"
  order: 911015
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-911-METHOD-ENFORCEMENT.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "911016"
    seclang.kubewaf.io/order: "911016"
    seclang.kubewaf.io/phase: "2"
  name: crs-911016
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REQUEST-911-METHOD-ENFORCEMENT
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "3"
  metadata:
    id: 911016
    phase: "2"
  order: 911016
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-911-METHOD-ENFORCEMENT.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "911017"
    seclang.kubewaf.io/order: "911017"
    seclang.kubewaf.io/phase: "1"
  name: crs-911017
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REQUEST-911-METHOD-ENFORCEMENT
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "4"
  metadata:
    comment: |+
      -= Paranoia Level 3 =- (apply only when tx.detection_paranoia_level is sufficiently high: 3 or higher)

    id: 911017
    phase: "1"
  order: 911017
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-911-METHOD-ENFORCEMENT.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "911018"
    seclang.kubewaf.io/order: "911018"
    seclang.kubewaf.io/phase: "2"
  name: crs-911018
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REQUEST-911-METHOD-ENFORCEMENT
    non-disruptive:
    - nonDisruptiveActionType: nolog
  markerAfter: END-REQUEST-911-METHOD-ENFORCEMENT
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "4"
  metadata:
    id: 911018
    phase: "2"
  order: 911018
