apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-913-SCANNER-DETECTION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "913011"
    seclang.kubewaf.io/order: "913011"
    seclang.kubewaf.io/phase: "1"
  name: crs-913011
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REQUEST-913-SCANNER-DETECTION
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "1"
  metadata:
    id: 913011
    phase: "1"
  order: 913011
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-913-SCANNER-DETECTION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "913012"
    seclang.kubewaf.io/order: "913012"
    seclang.kubewaf.io/phase: "2"
  name: crs-913012
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REQUEST-913-SCANNER-DETECTION
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "1"
  metadata:
    id: 913012
    phase: "2"
  order: 913012
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-913-SCANNER-DETECTION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "913100"
    seclang.kubewaf.io/order: "913100"
    seclang.kubewaf.io/phase: "1"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.attack-reputation-scanner: "true"
    seclang.kubewaf.io/tag.capec.1000.118.224.541.310: "true"
    seclang.kubewaf.io/tag.language-multi: "true"
    seclang.kubewaf.io/tag.owasp_crs.scanner-detection: "true"
    seclang.kubewaf.io/tag.paranoia-level.1: "true"
    seclang.kubewaf.io/tag.platform-multi: "true"
  name: crs-913100
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: capture
    - nonDisruptiveActionType: logdata
      value: 'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}'
    - nonDisruptiveActionType: setvar
      value: TX.inbound_anomaly_score_pl1=+%{tx.critical_anomaly_score}
  match:
  - collections:
    - arguments:
      - User-Agent
      name: REQUEST_HEADERS
    operator:
      name: pmFromFile
      value: scanners-user-agents.data
    transformations:
    - none
  metadata:
    id: 913100
    message: Found User-Agent associated with security scanner
    phase: "1"
    severity: CRITICAL
    tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-reputation-scanner
    - paranoia-level/1
    - OWASP_CRS/SCANNER-DETECTION
    - capec/1000/118/224/541/310
  order: 913100
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-913-SCANNER-DETECTION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "913013"
    seclang.kubewaf.io/order: "913013"
    seclang.kubewaf.io/phase: "1"
  name: crs-913013
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REQUEST-913-SCANNER-DETECTION
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "2"
  metadata:
    id: 913013
    phase: "1"
  order: 913013
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-913-SCANNER-DETECTION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "913014"
    seclang.kubewaf.io/order: "913014"
    seclang.kubewaf.io/phase: "2"
  name: crs-913014
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REQUEST-913-SCANNER-DETECTION
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "2"
  metadata:
    id: 913014
    phase: "2"
  order: 913014
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-913-SCANNER-DETECTION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "913015"
    seclang.kubewaf.io/order: "913015"
    seclang.kubewaf.io/phase: "1"
  name: crs-913015
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REQUEST-913-SCANNER-DETECTION
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "3"
  metadata:
    comment: |+
      -= Paranoia Level 2 =- (apply only when tx.detection_paranoia_level is sufficiently high: 2 or higher)

    id: 913015
    phase: "1"
  order: 913015
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-913-SCANNER-DETECTION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "913016"
    seclang.kubewaf.io/order: "913016"
    seclang.kubewaf.io/phase: "2"
  name: crs-913016
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REQUEST-913-SCANNER-DETECTION
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "3"
  metadata:
    id: 913016
    phase: "2"
  order: 913016
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-913-SCANNER-DETECTION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "913017"
    seclang.kubewaf.io/order: "913017"
    seclang.kubewaf.io/phase: "1"
  name: crs-913017
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REQUEST-913-SCANNER-DETECTION
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "4"
  metadata:
    comment: |+
      -= Paranoia Level 3 =- (apply only when tx.detection_paranoia_level is sufficiently high: 3 or higher)

    id: 913017
    phase: "1"
  order: 913017
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-913-SCANNER-DETECTION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "913018"
    seclang.kubewaf.io/order: "913018"
    seclang.kubewaf.io/phase: "2"
  name: crs-913018
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REQUEST-913-SCANNER-DETECTION
    non-disruptive:
    - nonDisruptiveActionType: nolog
  markerAfter: END-REQUEST-913-SCANNER-DETECTION
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "4"
  metadata:
    id: 913018
    phase: "2"
  order: 913018
