apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-956-DATA-LEAKAGES-RUBY.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "956010"
    seclang.kubewaf.io/order: "956010"
    seclang.kubewaf.io/phase: "4"
    seclang.kubewaf.io/tag.owasp_crs.data-leakages-ruby: "true"
  name: crs-956010
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-956-DATA-LEAKAGES-RUBY
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - Content-Encoding
      name: RESPONSE_HEADERS
    operator:
      name: pm
      value: gzip compress deflate br zstd
  metadata:
    id: 956010
    phase: "4"
    tags:
    - OWASP_CRS/DATA-LEAKAGES-RUBY
  order: 956010
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-956-DATA-LEAKAGES-RUBY.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "956011"
    seclang.kubewaf.io/order: "956011"
    seclang.kubewaf.io/phase: "3"
  name: crs-956011
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-956-DATA-LEAKAGES-RUBY
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "1"
  metadata:
    id: 956011
    phase: "3"
  order: 956011
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-956-DATA-LEAKAGES-RUBY.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "956012"
    seclang.kubewaf.io/order: "956012"
    seclang.kubewaf.io/phase: "4"
  name: crs-956012
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-956-DATA-LEAKAGES-RUBY
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "1"
  metadata:
    id: 956012
    phase: "4"
  order: 956012
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-956-DATA-LEAKAGES-RUBY.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "956100"
    seclang.kubewaf.io/order: "956100"
    seclang.kubewaf.io/phase: "4"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.attack-disclosure: "true"
    seclang.kubewaf.io/tag.capec.1000.118.116: "true"
    seclang.kubewaf.io/tag.language-ruby: "true"
    seclang.kubewaf.io/tag.owasp_crs.data-leakages-ruby: "true"
    seclang.kubewaf.io/tag.paranoia-level.1: "true"
    seclang.kubewaf.io/tag.platform-multi: "true"
  name: crs-956100
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: capture
    - nonDisruptiveActionType: logdata
      value: 'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}'
    - nonDisruptiveActionType: setvar
      value: TX.outbound_anomaly_score_pl1=+%{tx.error_anomaly_score}
  match:
  - operator:
      name: pmFromFile
      value: ruby-errors.data
    transformations:
    - none
    variables:
    - name: RESPONSE_BODY
  metadata:
    id: 956100
    message: RUBY Information Leakage
    phase: "4"
    severity: ERROR
    tags:
    - application-multi
    - language-ruby
    - platform-multi
    - attack-disclosure
    - paranoia-level/1
    - OWASP_CRS/DATA-LEAKAGES-RUBY
    - capec/1000/118/116
  order: 956100
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-956-DATA-LEAKAGES-RUBY.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "956013"
    seclang.kubewaf.io/order: "956013"
    seclang.kubewaf.io/phase: "3"
  name: crs-956013
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-956-DATA-LEAKAGES-RUBY
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "2"
  metadata:
    id: 956013
    phase: "3"
  order: 956013
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-956-DATA-LEAKAGES-RUBY.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "956014"
    seclang.kubewaf.io/order: "956014"
    seclang.kubewaf.io/phase: "4"
  name: crs-956014
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-956-DATA-LEAKAGES-RUBY
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "2"
  metadata:
    id: 956014
    phase: "4"
  order: 956014
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-956-DATA-LEAKAGES-RUBY.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "956110"
    seclang.kubewaf.io/order: "956110"
    seclang.kubewaf.io/phase: "4"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.attack-disclosure: "true"
    seclang.kubewaf.io/tag.capec.1000.118.116: "true"
    seclang.kubewaf.io/tag.language-ruby: "true"
    seclang.kubewaf.io/tag.owasp_crs.data-leakages-ruby: "true"
    seclang.kubewaf.io/tag.paranoia-level.2: "true"
    seclang.kubewaf.io/tag.platform-multi: "true"
  name: crs-956110
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: capture
    - nonDisruptiveActionType: logdata
      value: 'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}'
    - nonDisruptiveActionType: setvar
      value: TX.outbound_anomaly_score_pl2=+%{tx.error_anomaly_score}
  match:
  - operator:
      name: rx
      value: (?i)(?:<%[=#\s]|#\{[^}]+\})
    transformations:
    - none
    variables:
    - name: RESPONSE_BODY
  metadata:
    comment: |+
      Detect the presence of the Ruby ERB templates "<%", "<%= " and slim interpolation "#{}" in output.

      To prevent false positives (due to the short "<%" sequences), we also check for [#=\s] after an opening tag.

      This rule is placed at PL-2 since it also matches common templating format with various JavaScript templating engines.

    id: 956110
    message: Ruby source code leakage
    phase: "4"
    severity: ERROR
    tags:
    - application-multi
    - language-ruby
    - platform-multi
    - attack-disclosure
    - paranoia-level/2
    - OWASP_CRS/DATA-LEAKAGES-RUBY
    - capec/1000/118/116
  order: 956110
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-956-DATA-LEAKAGES-RUBY.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "956015"
    seclang.kubewaf.io/order: "956015"
    seclang.kubewaf.io/phase: "3"
  name: crs-956015
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-956-DATA-LEAKAGES-RUBY
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "3"
  metadata:
    id: 956015
    phase: "3"
  order: 956015
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-956-DATA-LEAKAGES-RUBY.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "956016"
    seclang.kubewaf.io/order: "956016"
    seclang.kubewaf.io/phase: "4"
  name: crs-956016
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-956-DATA-LEAKAGES-RUBY
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "3"
  metadata:
    id: 956016
    phase: "4"
  order: 956016
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-956-DATA-LEAKAGES-RUBY.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "956017"
    seclang.kubewaf.io/order: "956017"
    seclang.kubewaf.io/phase: "3"
  name: crs-956017
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-956-DATA-LEAKAGES-RUBY
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "4"
  metadata:
    comment: |+
      -= Paranoia Level 3 =- (apply only when tx.detection_paranoia_level is sufficiently high: 3 or higher)

    id: 956017
    phase: "3"
  order: 956017
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-956-DATA-LEAKAGES-RUBY.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "956018"
    seclang.kubewaf.io/order: "956018"
    seclang.kubewaf.io/phase: "4"
  name: crs-956018
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-956-DATA-LEAKAGES-RUBY
    non-disruptive:
    - nonDisruptiveActionType: nolog
  markerAfter: END-RESPONSE-956-DATA-LEAKAGES-RUBY
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "4"
  metadata:
    id: 956018
    phase: "4"
  order: 956018
