apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-954-DATA-LEAKAGES-IIS.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "954010"
    seclang.kubewaf.io/order: "954010"
    seclang.kubewaf.io/phase: "4"
    seclang.kubewaf.io/tag.owasp_crs.data-leakages-iis: "true"
  name: crs-954010
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-954-DATA-LEAKAGES-IIS
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - Content-Encoding
      name: RESPONSE_HEADERS
    operator:
      name: pm
      value: gzip compress deflate br zstd
  metadata:
    id: 954010
    phase: "4"
    tags:
    - OWASP_CRS/DATA-LEAKAGES-IIS
  order: 954010
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-954-DATA-LEAKAGES-IIS.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "954011"
    seclang.kubewaf.io/order: "954011"
    seclang.kubewaf.io/phase: "3"
  name: crs-954011
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-954-DATA-LEAKAGES-IIS
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "1"
  metadata:
    id: 954011
    phase: "3"
  order: 954011
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-954-DATA-LEAKAGES-IIS.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "954012"
    seclang.kubewaf.io/order: "954012"
    seclang.kubewaf.io/phase: "4"
  name: crs-954012
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-954-DATA-LEAKAGES-IIS
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "1"
  metadata:
    id: 954012
    phase: "4"
  order: 954012
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-954-DATA-LEAKAGES-IIS.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "954100"
    seclang.kubewaf.io/order: "954100"
    seclang.kubewaf.io/phase: "4"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.attack-disclosure: "true"
    seclang.kubewaf.io/tag.capec.1000.118.116: "true"
    seclang.kubewaf.io/tag.language-multi: "true"
    seclang.kubewaf.io/tag.owasp_crs.data-leakages-iis: "true"
    seclang.kubewaf.io/tag.paranoia-level.1: "true"
    seclang.kubewaf.io/tag.platform-iis: "true"
    seclang.kubewaf.io/tag.platform-windows: "true"
  name: crs-954100
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: capture
    - nonDisruptiveActionType: logdata
      value: 'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}'
    - nonDisruptiveActionType: setvar
      value: TX.outbound_anomaly_score_pl1=+%{tx.error_anomaly_score}
  match:
  - operator:
      name: rx
      value: (?i)[a-z]:[\x5c/]inetpub\b
    transformations:
    - none
    variables:
    - name: RESPONSE_BODY
  metadata:
    id: 954100
    message: Disclosure of IIS install location
    phase: "4"
    severity: ERROR
    tags:
    - application-multi
    - language-multi
    - platform-iis
    - platform-windows
    - attack-disclosure
    - paranoia-level/1
    - OWASP_CRS/DATA-LEAKAGES-IIS
    - capec/1000/118/116
  order: 954100
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-954-DATA-LEAKAGES-IIS.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "954110"
    seclang.kubewaf.io/order: "954110"
    seclang.kubewaf.io/phase: "4"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.attack-disclosure: "true"
    seclang.kubewaf.io/tag.capec.1000.118.116: "true"
    seclang.kubewaf.io/tag.language-multi: "true"
    seclang.kubewaf.io/tag.owasp_crs.data-leakages-iis: "true"
    seclang.kubewaf.io/tag.paranoia-level.1: "true"
    seclang.kubewaf.io/tag.platform-iis: "true"
    seclang.kubewaf.io/tag.platform-windows: "true"
  name: crs-954110
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: capture
    - nonDisruptiveActionType: logdata
      value: 'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}'
    - nonDisruptiveActionType: setvar
      value: TX.outbound_anomaly_score_pl1=+%{tx.error_anomaly_score}
  match:
  - operator:
      name: rx
      value: '(?:Microsoft OLE DB Provider for SQL Server(?:</font>.{1,20}?error ''800(?:04005|40e31)''.{1,40}?Timeout
        expired| \(0x80040e31\)<br>Timeout expired<br>)|<h1>internal server error</h1>.*?<h2>part
        of the server has crashed or it has a configuration error\.</h2>|cannot connect
        to the server: timed out)'
    transformations:
    - none
    variables:
    - name: RESPONSE_BODY
  metadata:
    id: 954110
    message: Application Availability Error
    phase: "4"
    severity: ERROR
    tags:
    - application-multi
    - language-multi
    - platform-iis
    - platform-windows
    - attack-disclosure
    - paranoia-level/1
    - OWASP_CRS/DATA-LEAKAGES-IIS
    - capec/1000/118/116
  order: 954110
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-954-DATA-LEAKAGES-IIS.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "954120"
    seclang.kubewaf.io/order: "954120"
    seclang.kubewaf.io/phase: "4"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.attack-disclosure: "true"
    seclang.kubewaf.io/tag.capec.1000.118.116: "true"
    seclang.kubewaf.io/tag.language-multi: "true"
    seclang.kubewaf.io/tag.owasp_crs.data-leakages-iis: "true"
    seclang.kubewaf.io/tag.paranoia-level.1: "true"
    seclang.kubewaf.io/tag.platform-iis: "true"
    seclang.kubewaf.io/tag.platform-windows: "true"
  name: crs-954120
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: capture
    - nonDisruptiveActionType: logdata
      value: 'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}'
    - nonDisruptiveActionType: setvar
      value: TX.outbound_anomaly_score_pl1=+%{tx.error_anomaly_score}
  match:
  - operator:
      name: pmFromFile
      value: iis-errors.data
    transformations:
    - none
    variables:
    - name: RESPONSE_BODY
  metadata:
    comment: |+
      IIS Errors leakage

    id: 954120
    message: IIS Information Leakage
    phase: "4"
    severity: ERROR
    tags:
    - application-multi
    - language-multi
    - platform-iis
    - platform-windows
    - attack-disclosure
    - paranoia-level/1
    - OWASP_CRS/DATA-LEAKAGES-IIS
    - capec/1000/118/116
  order: 954120
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-954-DATA-LEAKAGES-IIS.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "954130"
    seclang.kubewaf.io/order: "954130"
    seclang.kubewaf.io/phase: "4"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.attack-disclosure: "true"
    seclang.kubewaf.io/tag.capec.1000.118.116: "true"
    seclang.kubewaf.io/tag.language-multi: "true"
    seclang.kubewaf.io/tag.owasp_crs.data-leakages-iis: "true"
    seclang.kubewaf.io/tag.paranoia-level.1: "true"
    seclang.kubewaf.io/tag.platform-iis: "true"
    seclang.kubewaf.io/tag.platform-windows: "true"
  name: crs-954130
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: capture
    - nonDisruptiveActionType: logdata
      value: 'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}'
  match:
  - operator:
      name: rx
      negate: true
      value: ^404$
    transformations:
    - none
    variables:
    - name: RESPONSE_STATUS
  - actions:

      non-disruptive:
      - nonDisruptiveActionType: capture
      - nonDisruptiveActionType: setvar
        value: TX.outbound_anomaly_score_pl1=+%{tx.error_anomaly_score}
    operator:
      name: rx
      value: \bServer Error in.{0,50}?\bApplication\b
    transformations:
    - none
    variables:
    - name: RESPONSE_BODY
  metadata:
    id: 954130
    message: IIS Information Leakage
    phase: "4"
    severity: ERROR
    tags:
    - application-multi
    - language-multi
    - platform-iis
    - platform-windows
    - attack-disclosure
    - paranoia-level/1
    - OWASP_CRS/DATA-LEAKAGES-IIS
    - capec/1000/118/116
  order: 954130
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-954-DATA-LEAKAGES-IIS.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "954013"
    seclang.kubewaf.io/order: "954013"
    seclang.kubewaf.io/phase: "3"
  name: crs-954013
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-954-DATA-LEAKAGES-IIS
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "2"
  metadata:
    id: 954013
    phase: "3"
  order: 954013
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-954-DATA-LEAKAGES-IIS.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "954014"
    seclang.kubewaf.io/order: "954014"
    seclang.kubewaf.io/phase: "4"
  name: crs-954014
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-954-DATA-LEAKAGES-IIS
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "2"
  metadata:
    id: 954014
    phase: "4"
  order: 954014
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-954-DATA-LEAKAGES-IIS.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "954101"
    seclang.kubewaf.io/order: "954101"
    seclang.kubewaf.io/phase: "4"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.attack-disclosure: "true"
    seclang.kubewaf.io/tag.capec.1000.118.116: "true"
    seclang.kubewaf.io/tag.language-multi: "true"
    seclang.kubewaf.io/tag.owasp_crs.data-leakages-iis: "true"
    seclang.kubewaf.io/tag.paranoia-level.2: "true"
    seclang.kubewaf.io/tag.platform-iis: "true"
    seclang.kubewaf.io/tag.platform-windows: "true"
  name: crs-954101
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: capture
    - nonDisruptiveActionType: logdata
      value: 'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}'
    - nonDisruptiveActionType: setvar
      value: TX.outbound_anomaly_score_pl2=+%{tx.error_anomaly_score}
  match:
  - operator:
      name: rx
      value: (?i)[\x5c/]inetpub\b
    transformations:
    - none
    variables:
    - name: RESPONSE_BODY
  metadata:
    id: 954101
    message: Disclosure of IIS install location
    phase: "4"
    severity: ERROR
    tags:
    - application-multi
    - language-multi
    - platform-iis
    - platform-windows
    - attack-disclosure
    - paranoia-level/2
    - OWASP_CRS/DATA-LEAKAGES-IIS
    - capec/1000/118/116
  order: 954101
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-954-DATA-LEAKAGES-IIS.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "954015"
    seclang.kubewaf.io/order: "954015"
    seclang.kubewaf.io/phase: "3"
  name: crs-954015
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-954-DATA-LEAKAGES-IIS
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "3"
  metadata:
    id: 954015
    phase: "3"
  order: 954015
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-954-DATA-LEAKAGES-IIS.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "954016"
    seclang.kubewaf.io/order: "954016"
    seclang.kubewaf.io/phase: "4"
  name: crs-954016
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-954-DATA-LEAKAGES-IIS
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "3"
  metadata:
    id: 954016
    phase: "4"
  order: 954016
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-954-DATA-LEAKAGES-IIS.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "954017"
    seclang.kubewaf.io/order: "954017"
    seclang.kubewaf.io/phase: "3"
  name: crs-954017
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-954-DATA-LEAKAGES-IIS
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "4"
  metadata:
    comment: |+
      -= Paranoia Level 3 =- (apply only when tx.detection_paranoia_level is sufficiently high: 3 or higher)

    id: 954017
    phase: "3"
  order: 954017
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-954-DATA-LEAKAGES-IIS.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "954018"
    seclang.kubewaf.io/order: "954018"
    seclang.kubewaf.io/phase: "4"
  name: crs-954018
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-954-DATA-LEAKAGES-IIS
    non-disruptive:
    - nonDisruptiveActionType: nolog
  markerAfter: END-RESPONSE-954-DATA-LEAKAGES-IIS
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "4"
  metadata:
    id: 954018
    phase: "4"
  order: 954018
