apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-953-DATA-LEAKAGES-PHP.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "953010"
    seclang.kubewaf.io/order: "953010"
    seclang.kubewaf.io/phase: "4"
    seclang.kubewaf.io/tag.owasp_crs.data-leakages-php: "true"
  name: crs-953010
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-953-DATA-LEAKAGES-PHP
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - Content-Encoding
      name: RESPONSE_HEADERS
    operator:
      name: pm
      value: gzip compress deflate br zstd
  metadata:
    id: 953010
    phase: "4"
    tags:
    - OWASP_CRS/DATA-LEAKAGES-PHP
  order: 953010
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-953-DATA-LEAKAGES-PHP.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "953011"
    seclang.kubewaf.io/order: "953011"
    seclang.kubewaf.io/phase: "3"
  name: crs-953011
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-953-DATA-LEAKAGES-PHP
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "1"
  metadata:
    id: 953011
    phase: "3"
  order: 953011
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-953-DATA-LEAKAGES-PHP.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "953012"
    seclang.kubewaf.io/order: "953012"
    seclang.kubewaf.io/phase: "4"
  name: crs-953012
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-953-DATA-LEAKAGES-PHP
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "1"
  metadata:
    id: 953012
    phase: "4"
  order: 953012
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-953-DATA-LEAKAGES-PHP.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "953100"
    seclang.kubewaf.io/order: "953100"
    seclang.kubewaf.io/phase: "4"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.attack-disclosure: "true"
    seclang.kubewaf.io/tag.capec.1000.118.116: "true"
    seclang.kubewaf.io/tag.language-php: "true"
    seclang.kubewaf.io/tag.owasp_crs.data-leakages-php: "true"
    seclang.kubewaf.io/tag.paranoia-level.1: "true"
    seclang.kubewaf.io/tag.platform-multi: "true"
  name: crs-953100
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: capture
    - nonDisruptiveActionType: logdata
      value: 'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}'
    - nonDisruptiveActionType: setvar
      value: TX.outbound_anomaly_score_pl1=+%{tx.error_anomaly_score}
  match:
  - operator:
      name: pmFromFile
      value: php-errors.data
    transformations:
    - none
    variables:
    - name: RESPONSE_BODY
  metadata:
    id: 953100
    message: PHP Information Leakage
    phase: "4"
    severity: ERROR
    tags:
    - application-multi
    - language-php
    - platform-multi
    - attack-disclosure
    - paranoia-level/1
    - OWASP_CRS/DATA-LEAKAGES-PHP
    - capec/1000/118/116
  order: 953100
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-953-DATA-LEAKAGES-PHP.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "953110"
    seclang.kubewaf.io/order: "953110"
    seclang.kubewaf.io/phase: "4"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.attack-disclosure: "true"
    seclang.kubewaf.io/tag.capec.1000.118.116: "true"
    seclang.kubewaf.io/tag.language-php: "true"
    seclang.kubewaf.io/tag.owasp_crs.data-leakages-php: "true"
    seclang.kubewaf.io/tag.paranoia-level.1: "true"
    seclang.kubewaf.io/tag.platform-multi: "true"
  name: crs-953110
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: capture
    - nonDisruptiveActionType: logdata
      value: 'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}'
    - nonDisruptiveActionType: setvar
      value: TX.outbound_anomaly_score_pl1=+%{tx.error_anomaly_score}
  match:
  - operator:
      name: rx
      value: (?:\b(?:f(?:tp_(?:nb_)?f?(?:ge|pu)t|get(?:s?s|c)|scanf|write|open|read)|gz(?:(?:encod|writ)e|compress|open|read)|s(?:ession_start|candir)|read(?:(?:gz)?file|dir)|move_uploaded_file|(?:proc_|bz)open|call_user_func)|\$_(?:(?:pos|ge)t|session))\b
    transformations:
    - none
    variables:
    - name: RESPONSE_BODY
  metadata:
    comment: |+
      -=[ PHP source code leakage ]=-

      Detect some common PHP keywords in output.

    id: 953110
    message: PHP source code leakage
    phase: "4"
    severity: ERROR
    tags:
    - application-multi
    - language-php
    - platform-multi
    - attack-disclosure
    - paranoia-level/1
    - OWASP_CRS/DATA-LEAKAGES-PHP
    - capec/1000/118/116
  order: 953110
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-953-DATA-LEAKAGES-PHP.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "953120"
    seclang.kubewaf.io/order: "953120"
    seclang.kubewaf.io/phase: "4"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.attack-disclosure: "true"
    seclang.kubewaf.io/tag.capec.1000.118.116: "true"
    seclang.kubewaf.io/tag.language-php: "true"
    seclang.kubewaf.io/tag.owasp_crs.data-leakages-php: "true"
    seclang.kubewaf.io/tag.paranoia-level.1: "true"
    seclang.kubewaf.io/tag.platform-multi: "true"
  name: crs-953120
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: capture
    - nonDisruptiveActionType: logdata
      value: 'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}'
    - nonDisruptiveActionType: setvar
      value: TX.outbound_anomaly_score_pl1=+%{tx.error_anomaly_score}
  match:
  - operator:
      name: rx
      value: (?i)<\?(?:=|php)?\s+
    transformations:
    - none
    variables:
    - name: RESPONSE_BODY
  metadata:
    comment: |+
      Detect the presence of the PHP open tag "<? ", "<?= " or "<?php " in output.

      To prevent false positives (due to the short "<?" sequences), we also include,
      the space after it in an attempt to stop alerts in binary output.
      And we make it case insensitive.

    id: 953120
    message: PHP source code leakage
    phase: "4"
    severity: ERROR
    tags:
    - application-multi
    - language-php
    - platform-multi
    - attack-disclosure
    - paranoia-level/1
    - OWASP_CRS/DATA-LEAKAGES-PHP
    - capec/1000/118/116
  order: 953120
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-953-DATA-LEAKAGES-PHP.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "953013"
    seclang.kubewaf.io/order: "953013"
    seclang.kubewaf.io/phase: "3"
  name: crs-953013
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-953-DATA-LEAKAGES-PHP
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "2"
  metadata:
    id: 953013
    phase: "3"
  order: 953013
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-953-DATA-LEAKAGES-PHP.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "953014"
    seclang.kubewaf.io/order: "953014"
    seclang.kubewaf.io/phase: "4"
  name: crs-953014
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-953-DATA-LEAKAGES-PHP
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "2"
  metadata:
    id: 953014
    phase: "4"
  order: 953014
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-953-DATA-LEAKAGES-PHP.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "953101"
    seclang.kubewaf.io/order: "953101"
    seclang.kubewaf.io/phase: "4"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.attack-disclosure: "true"
    seclang.kubewaf.io/tag.capec.1000.118.116: "true"
    seclang.kubewaf.io/tag.language-php: "true"
    seclang.kubewaf.io/tag.owasp_crs.data-leakages-php: "true"
    seclang.kubewaf.io/tag.paranoia-level.2: "true"
    seclang.kubewaf.io/tag.platform-multi: "true"
  name: crs-953101
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: capture
    - nonDisruptiveActionType: logdata
      value: 'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}'
    - nonDisruptiveActionType: setvar
      value: TX.outbound_anomaly_score_pl2=+%{tx.error_anomaly_score}
  match:
  - operator:
      name: rx
      value: (?i)Empty string|F(?:ile size is|reeing memory)|Header (?:name )?\"|Invalid
        date|No active class|(?:Out of memor|cannot be empt)y|Pa(?:ir level|ssword
        is too long)|Re(?:ading file|starting!)|S(?:ession is not active|tatic function\b)|T(?:elling\.\.\.|he
        function\b)|(?:Unknown reas|invalid opti)on|e(?:mpty password|rror reading)
    transformations:
    - none
    variables:
    - name: RESPONSE_BODY
  metadata:
    id: 953101
    message: PHP Information Leakage
    phase: "4"
    severity: ERROR
    tags:
    - application-multi
    - language-php
    - platform-multi
    - attack-disclosure
    - paranoia-level/2
    - OWASP_CRS/DATA-LEAKAGES-PHP
    - capec/1000/118/116
  order: 953101
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-953-DATA-LEAKAGES-PHP.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "953015"
    seclang.kubewaf.io/order: "953015"
    seclang.kubewaf.io/phase: "3"
  name: crs-953015
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-953-DATA-LEAKAGES-PHP
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "3"
  metadata:
    id: 953015
    phase: "3"
  order: 953015
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-953-DATA-LEAKAGES-PHP.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "953016"
    seclang.kubewaf.io/order: "953016"
    seclang.kubewaf.io/phase: "4"
  name: crs-953016
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-953-DATA-LEAKAGES-PHP
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "3"
  metadata:
    id: 953016
    phase: "4"
  order: 953016
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-953-DATA-LEAKAGES-PHP.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "953017"
    seclang.kubewaf.io/order: "953017"
    seclang.kubewaf.io/phase: "3"
  name: crs-953017
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-953-DATA-LEAKAGES-PHP
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "4"
  metadata:
    comment: |+
      -= Paranoia Level 3 =- (apply only when tx.detection_paranoia_level is sufficiently high: 3 or higher)

    id: 953017
    phase: "3"
  order: 953017
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-953-DATA-LEAKAGES-PHP.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "953018"
    seclang.kubewaf.io/order: "953018"
    seclang.kubewaf.io/phase: "4"
  name: crs-953018
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-953-DATA-LEAKAGES-PHP
    non-disruptive:
    - nonDisruptiveActionType: nolog
  markerAfter: END-RESPONSE-953-DATA-LEAKAGES-PHP
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "4"
  metadata:
    id: 953018
    phase: "4"
  order: 953018
