apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-931-APPLICATION-ATTACK-RFI.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "931011"
    seclang.kubewaf.io/order: "931011"
    seclang.kubewaf.io/phase: "1"
  name: crs-931011
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REQUEST-931-APPLICATION-ATTACK-RFI
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "1"
  metadata:
    id: 931011
    phase: "1"
  order: 931011
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-931-APPLICATION-ATTACK-RFI.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "931012"
    seclang.kubewaf.io/order: "931012"
    seclang.kubewaf.io/phase: "2"
  name: crs-931012
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REQUEST-931-APPLICATION-ATTACK-RFI
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "1"
  metadata:
    id: 931012
    phase: "2"
  order: 931012
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-931-APPLICATION-ATTACK-RFI.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "931100"
    seclang.kubewaf.io/order: "931100"
    seclang.kubewaf.io/phase: "2"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.attack-rfi: "true"
    seclang.kubewaf.io/tag.capec.1000.152.175.253: "true"
    seclang.kubewaf.io/tag.language-multi: "true"
    seclang.kubewaf.io/tag.owasp_crs.attack-rfi: "true"
    seclang.kubewaf.io/tag.paranoia-level.1: "true"
    seclang.kubewaf.io/tag.platform-multi: "true"
  name: crs-931100
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: capture
    - nonDisruptiveActionType: logdata
      value: 'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}'
    - nonDisruptiveActionType: setvar
      value: TX.rfi_score=+%{tx.critical_anomaly_score}
    - nonDisruptiveActionType: setvar
      value: TX.inbound_anomaly_score_pl1=+%{tx.critical_anomaly_score}
  match:
  - collections:
    - name: ARGS
    - arguments:
      - /*
      name: XML
    operator:
      name: rx
      value: (?i)^(f(?:ile|tps?)|https?|ssh)://(?:\[?[0-9a-f]+:[0-:a-f]+\]?|[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})
    transformations:
    - none
    - urlDecodeUni
  metadata:
    id: 931100
    message: 'Possible Remote File Inclusion (RFI) Attack: URL Parameter using IP
      Address'
    phase: "2"
    severity: CRITICAL
    tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-rfi
    - paranoia-level/1
    - OWASP_CRS/ATTACK-RFI
    - capec/1000/152/175/253
  order: 931100
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-931-APPLICATION-ATTACK-RFI.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "931110"
    seclang.kubewaf.io/order: "931110"
    seclang.kubewaf.io/phase: "2"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.attack-rfi: "true"
    seclang.kubewaf.io/tag.capec.1000.152.175.253: "true"
    seclang.kubewaf.io/tag.language-multi: "true"
    seclang.kubewaf.io/tag.owasp_crs.attack-rfi: "true"
    seclang.kubewaf.io/tag.paranoia-level.1: "true"
    seclang.kubewaf.io/tag.platform-multi: "true"
  name: crs-931110
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: capture
    - nonDisruptiveActionType: logdata
      value: 'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}'
    - nonDisruptiveActionType: setvar
      value: TX.rfi_score=+%{tx.critical_anomaly_score}
    - nonDisruptiveActionType: setvar
      value: TX.inbound_anomaly_score_pl1=+%{tx.critical_anomaly_score}
  match:
  - operator:
      name: rx
      value: (?i)(?:\binclude[\s\x0b]*\([^\)]*|mosConfig_absolute_path|(?:_(?:CONF\[path|SERVER\[DOCUMENT_ROOT)|path\[docroot|config\[root_dir)\]|GALLERY_BASEDIR|appserv_root)=(?:f(?:ile|tps?)|https?)://
    transformations:
    - none
    - urlDecodeUni
    variables:
    - name: QUERY_STRING
    - name: REQUEST_BODY
  metadata:
    comment: |+
      Regular expression generated from regex-assembly/931110.ra.
      To update the regular expression run the following shell script
      (consult https://coreruleset.org/docs/development/regex_assembly/ for details):
        crs-toolchain regex update 931110

    id: 931110
    message: 'Possible Remote File Inclusion (RFI) Attack: Common RFI Vulnerable Parameter
      Name used w/URL Payload'
    phase: "2"
    severity: CRITICAL
    tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-rfi
    - paranoia-level/1
    - OWASP_CRS/ATTACK-RFI
    - capec/1000/152/175/253
  order: 931110
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-931-APPLICATION-ATTACK-RFI.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "931120"
    seclang.kubewaf.io/order: "931120"
    seclang.kubewaf.io/phase: "2"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.attack-rfi: "true"
    seclang.kubewaf.io/tag.capec.1000.152.175.253: "true"
    seclang.kubewaf.io/tag.language-multi: "true"
    seclang.kubewaf.io/tag.owasp_crs.attack-rfi: "true"
    seclang.kubewaf.io/tag.paranoia-level.1: "true"
    seclang.kubewaf.io/tag.platform-multi: "true"
  name: crs-931120
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: capture
    - nonDisruptiveActionType: logdata
      value: 'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}'
    - nonDisruptiveActionType: setvar
      value: TX.rfi_score=+%{tx.critical_anomaly_score}
    - nonDisruptiveActionType: setvar
      value: TX.inbound_anomaly_score_pl1=+%{tx.critical_anomaly_score}
  match:
  - collections:
    - name: ARGS
    operator:
      name: rx
      value: ^(?i:file|ftps?|https?).*?\?+$
    transformations:
    - none
  metadata:
    id: 931120
    message: 'Possible Remote File Inclusion (RFI) Attack: URL Payload Used w/Trailing
      Question Mark Character (?)'
    phase: "2"
    severity: CRITICAL
    tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-rfi
    - paranoia-level/1
    - OWASP_CRS/ATTACK-RFI
    - capec/1000/152/175/253
  order: 931120
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-931-APPLICATION-ATTACK-RFI.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "931013"
    seclang.kubewaf.io/order: "931013"
    seclang.kubewaf.io/phase: "1"
  name: crs-931013
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REQUEST-931-APPLICATION-ATTACK-RFI
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "2"
  metadata:
    id: 931013
    phase: "1"
  order: 931013
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-931-APPLICATION-ATTACK-RFI.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "931014"
    seclang.kubewaf.io/order: "931014"
    seclang.kubewaf.io/phase: "2"
  name: crs-931014
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REQUEST-931-APPLICATION-ATTACK-RFI
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "2"
  metadata:
    id: 931014
    phase: "2"
  order: 931014
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-931-APPLICATION-ATTACK-RFI.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "931130"
    seclang.kubewaf.io/order: "931130"
    seclang.kubewaf.io/phase: "2"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.attack-rfi: "true"
    seclang.kubewaf.io/tag.capec.1000.152.175.253: "true"
    seclang.kubewaf.io/tag.language-multi: "true"
    seclang.kubewaf.io/tag.owasp_crs.attack-rfi: "true"
    seclang.kubewaf.io/tag.paranoia-level.2: "true"
    seclang.kubewaf.io/tag.platform-multi: "true"
  name: crs-931130
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: capture
    - nonDisruptiveActionType: logdata
      value: 'Matched Data: %{TX.0} found within %{tx.original_target}: %{MATCHED_VAR}'
    - nonDisruptiveActionType: setvar
      value: TX.rfi_parameter_%{MATCHED_VAR_NAME}=.%{tx.1}
    - nonDisruptiveActionType: setvar
      value: TX.original_target=%{MATCHED_VAR_NAME}
  match:
  - collections:
    - name: ARGS
    operator:
      name: rx
      value: (?i)(?:(?:url|jar):)?(?:a(?:cap|f[ps]|ttachment)|b(?:eshare|itcoin|lob)|c(?:a(?:llto|p)|id|vs|ompress.(?:zlib|bzip2))|d(?:a(?:v|ta)|ict|n(?:s|tp))|e(?:d2k|xpect)|f(?:(?:ee)?d|i(?:le|nger|sh)|tps?)|g(?:it|o(?:pher)?|lob)|h(?:323|ttps?)|i(?:ax|cap|(?:ma|p)ps?|rc[6s]?)|ja(?:bbe)?r|l(?:dap[is]?|ocal_file)|m(?:a(?:ilto|ven)|ms|umble)|n(?:e(?:tdoc|ws)|fs|ntps?)|ogg|p(?:aparazzi|h(?:ar|p)|op(?:2|3s?)|r(?:es|oxy)|syc)|r(?:mi|sync|tm(?:f?p)?|ar)|s(?:3|ftp|ips?|m(?:[bs]|tps?)|n(?:ews|mp)|sh(?:2(?:.(?:s(?:hell|(?:ft|c)p)|exec|tunnel))?)?|vn(?:\+ssh)?)|t(?:e(?:amspeak|lnet)|ftp|urns?)|u(?:dp|nreal|t2004)|v(?:entrilo|iew-source|nc)|w(?:ebcal|ss?)|x(?:mpp|ri)|zip)://?(?:[^@]+@)?([^/]*)
    transformations:
    - none
  - actions:

      non-disruptive:
      - nonDisruptiveActionType: setvar
        value: TX.rfi_score=+%{tx.critical_anomaly_score}
      - nonDisruptiveActionType: setvar
        value: TX.inbound_anomaly_score_pl2=+%{tx.critical_anomaly_score}
    collections:
    - arguments:
      - /rfi_parameter_.*/
      name: TX
    operator:
      name: endsWith
      negate: true
      value: .%{request_headers.host}
  metadata:
    id: 931130
    message: 'Possible Remote File Inclusion (RFI) Attack: Off-Domain Reference/Link'
    phase: "2"
    severity: CRITICAL
    tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-rfi
    - paranoia-level/2
    - OWASP_CRS/ATTACK-RFI
    - capec/1000/152/175/253
  order: 931130
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-931-APPLICATION-ATTACK-RFI.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "931131"
    seclang.kubewaf.io/order: "931131"
    seclang.kubewaf.io/phase: "1"
    seclang.kubewaf.io/tag.application-multi: "true"
    seclang.kubewaf.io/tag.attack-rfi: "true"
    seclang.kubewaf.io/tag.capec.1000.152.175.253: "true"
    seclang.kubewaf.io/tag.language-multi: "true"
    seclang.kubewaf.io/tag.owasp_crs.attack-rfi: "true"
    seclang.kubewaf.io/tag.paranoia-level.2: "true"
    seclang.kubewaf.io/tag.platform-multi: "true"
  name: crs-931131
spec:
  actions:
    disruptive:
      disruptiveActionType: block
    non-disruptive:
    - nonDisruptiveActionType: capture
    - nonDisruptiveActionType: logdata
      value: 'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}'
    - nonDisruptiveActionType: setvar
      value: TX.inbound_anomaly_score_pl2=+%{tx.critical_anomaly_score}
  match:
  - operator:
      name: rx
      value: (?i)(?:(?:url|jar):)?(?:a(?:cap|f[ps]|ttachment)|b(?:eshare|itcoin|lob)|c(?:a(?:llto|p)|id|vs|ompress.(?:zlib|bzip2))|d(?:a(?:v|ta)|ict|n(?:s|tp))|e(?:d2k|xpect)|f(?:(?:ee)?d|i(?:le|nger|sh)|tps?)|g(?:it|o(?:pher)?|lob)|h(?:323|ttps?)|i(?:ax|cap|(?:ma|p)ps?|rc[6s]?)|ja(?:bbe)?r|l(?:dap[is]?|ocal_file)|m(?:a(?:ilto|ven)|ms|umble)|n(?:e(?:tdoc|ws)|fs|ntps?)|ogg|p(?:aparazzi|h(?:ar|p)|op(?:2|3s?)|r(?:es|oxy)|syc)|r(?:mi|sync|tm(?:f?p)?|ar)|s(?:3|ftp|ips?|m(?:[bs]|tps?)|n(?:ews|mp)|sh(?:2(?:.(?:s(?:hell|(?:ft|c)p)|exec|tunnel))?)?|vn(?:\+ssh)?)|t(?:e(?:amspeak|lnet)|ftp|urns?)|u(?:dp|nreal|t2004)|v(?:entrilo|iew-source|nc)|w(?:ebcal|ss?)|x(?:mpp|ri)|zip)://(?:[^@]+@)?([^/]*)
    transformations:
    - none
    - urlDecodeUni
    variables:
    - name: REQUEST_FILENAME
  metadata:
    comment: |+
      This is a sibling of 931130.

      Regular expression generated from regex-assembly/931131.ra.
      To update the regular expression run the following shell script
      (consult https://coreruleset.org/docs/development/regex_assembly/ for details):
        crs-toolchain regex update 931131

    id: 931131
    message: Possible Remote File Inclusion (RFI) Attack
    phase: "1"
    severity: CRITICAL
    tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-rfi
    - paranoia-level/2
    - OWASP_CRS/ATTACK-RFI
    - capec/1000/152/175/253
  order: 931131
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-931-APPLICATION-ATTACK-RFI.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "931015"
    seclang.kubewaf.io/order: "931015"
    seclang.kubewaf.io/phase: "1"
  name: crs-931015
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REQUEST-931-APPLICATION-ATTACK-RFI
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "3"
  metadata:
    id: 931015
    phase: "1"
  order: 931015
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-931-APPLICATION-ATTACK-RFI.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "931016"
    seclang.kubewaf.io/order: "931016"
    seclang.kubewaf.io/phase: "2"
  name: crs-931016
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REQUEST-931-APPLICATION-ATTACK-RFI
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "3"
  metadata:
    id: 931016
    phase: "2"
  order: 931016
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-931-APPLICATION-ATTACK-RFI.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "931017"
    seclang.kubewaf.io/order: "931017"
    seclang.kubewaf.io/phase: "1"
  name: crs-931017
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REQUEST-931-APPLICATION-ATTACK-RFI
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "4"
  metadata:
    comment: |+
      -= Paranoia Level 3 =- (apply only when tx.detection_paranoia_level is sufficiently high: 3 or higher)

    id: 931017
    phase: "1"
  order: 931017
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: REQUEST-931-APPLICATION-ATTACK-RFI.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "931018"
    seclang.kubewaf.io/order: "931018"
    seclang.kubewaf.io/phase: "2"
  name: crs-931018
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REQUEST-931-APPLICATION-ATTACK-RFI
    non-disruptive:
    - nonDisruptiveActionType: nolog
  markerAfter: END-REQUEST-931-APPLICATION-ATTACK-RFI
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "4"
  metadata:
    id: 931018
    phase: "2"
  order: 931018
