apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-980-CORRELATION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "980099"
    seclang.kubewaf.io/order: "980099"
    seclang.kubewaf.io/phase: "5"
  name: crs-980099
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    non-disruptive:
    - nonDisruptiveActionType: nolog
    - nonDisruptiveActionType: noauditlog
    - nonDisruptiveActionType: setvar
      value: TX.blocking_anomaly_score=%{tx.blocking_inbound_anomaly_score}
    - nonDisruptiveActionType: setvar
      value: TX.blocking_anomaly_score=+%{tx.blocking_outbound_anomaly_score}
    - nonDisruptiveActionType: setvar
      value: TX.detection_anomaly_score=%{tx.detection_inbound_anomaly_score}
    - nonDisruptiveActionType: setvar
      value: TX.detection_anomaly_score=+%{tx.detection_outbound_anomaly_score}
    - nonDisruptiveActionType: setvar
      value: TX.anomaly_score=%{tx.blocking_inbound_anomaly_score}
    - nonDisruptiveActionType: setvar
      value: TX.anomaly_score=+%{tx.blocking_outbound_anomaly_score}
  match:
  - always-match: true
    operator:
      name: unconditionalMatch
    transformations:
    - none
  metadata:
    id: 980099
    phase: "5"
  order: 980099
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-980-CORRELATION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "980041"
    seclang.kubewaf.io/order: "980041"
    seclang.kubewaf.io/phase: "5"
  name: crs-980041
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REPORTING
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - REPORTING_LEVEL
      name: TX
    operator:
      name: eq
      value: "0"
  metadata:
    id: 980041
    phase: "5"
  order: 980041
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-980-CORRELATION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "980042"
    seclang.kubewaf.io/order: "980042"
    seclang.kubewaf.io/phase: "5"
  name: crs-980042
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: LOG-REPORTING
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - REPORTING_LEVEL
      name: TX
    operator:
      name: ge
      value: "5"
  metadata:
    comment: |
      -= Reporting Level 5 =- (Jump to reporting rule immediately when tx.reporting_level is 5 or greater)
    id: 980042
    phase: "5"
  order: 980042
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-980-CORRELATION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "980043"
    seclang.kubewaf.io/order: "980043"
    seclang.kubewaf.io/phase: "5"
  name: crs-980043
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REPORTING
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_ANOMALY_SCORE
      name: TX
    operator:
      name: eq
      value: "0"
  metadata:
    comment: |
      -= Zero detection score =- (Skip over reporting when sum of inbound and outbound detection score is equal to 0)
    id: 980043
    phase: "5"
  order: 980043
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-980-CORRELATION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "980044"
    seclang.kubewaf.io/order: "980044"
    seclang.kubewaf.io/phase: "5"
  name: crs-980044
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: LOG-REPORTING
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - BLOCKING_INBOUND_ANOMALY_SCORE
      name: TX
    operator:
      name: ge
      value: '%{tx.inbound_anomaly_score_threshold}'
  metadata:
    comment: |
      -= Blocking score exceeds threshold =- (Jump to reporting rule immediately if a blocking score exceeds a threshold)
    id: 980044
    phase: "5"
  order: 980044
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-980-CORRELATION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "980045"
    seclang.kubewaf.io/order: "980045"
    seclang.kubewaf.io/phase: "5"
  name: crs-980045
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: LOG-REPORTING
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - BLOCKING_OUTBOUND_ANOMALY_SCORE
      name: TX
    operator:
      name: ge
      value: '%{tx.outbound_anomaly_score_threshold}'
  metadata:
    id: 980045
    phase: "5"
  order: 980045
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-980-CORRELATION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "980046"
    seclang.kubewaf.io/order: "980046"
    seclang.kubewaf.io/phase: "5"
  name: crs-980046
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REPORTING
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - REPORTING_LEVEL
      name: TX
    operator:
      name: lt
      value: "2"
  metadata:
    comment: |
      -= Reporting Level 2 =- (Skip over reporting when tx.reporting_level is less than 2)
    id: 980046
    phase: "5"
  order: 980046
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-980-CORRELATION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "980047"
    seclang.kubewaf.io/order: "980047"
    seclang.kubewaf.io/phase: "5"
  name: crs-980047
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: LOG-REPORTING
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_INBOUND_ANOMALY_SCORE
      name: TX
    operator:
      name: ge
      value: '%{tx.inbound_anomaly_score_threshold}'
  metadata:
    comment: |
      -= Detection score exceeds threshold =- (Jump to reporting rule immediately if a detection score exceeds a threshold)
    id: 980047
    phase: "5"
  order: 980047
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-980-CORRELATION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "980048"
    seclang.kubewaf.io/order: "980048"
    seclang.kubewaf.io/phase: "5"
  name: crs-980048
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: LOG-REPORTING
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_OUTBOUND_ANOMALY_SCORE
      name: TX
    operator:
      name: ge
      value: '%{tx.outbound_anomaly_score_threshold}'
  metadata:
    id: 980048
    phase: "5"
  order: 980048
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-980-CORRELATION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "980049"
    seclang.kubewaf.io/order: "980049"
    seclang.kubewaf.io/phase: "5"
  name: crs-980049
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REPORTING
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - REPORTING_LEVEL
      name: TX
    operator:
      name: lt
      value: "3"
  metadata:
    comment: |
      -= Reporting Level 3 =- (Skip over reporting when tx.reporting_level is less than 3)
    id: 980049
    phase: "5"
  order: 980049
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-980-CORRELATION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "980050"
    seclang.kubewaf.io/order: "980050"
    seclang.kubewaf.io/phase: "5"
  name: crs-980050
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: LOG-REPORTING
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - BLOCKING_ANOMALY_SCORE
      name: TX
    operator:
      name: gt
      value: "0"
  metadata:
    comment: |
      -= Blocking score greater than zero =- (Jump to reporting rule immediately when sum of inbound and outbound blocking score is greater than zero)
    id: 980050
    phase: "5"
  order: 980050
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-980-CORRELATION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "980051"
    seclang.kubewaf.io/order: "980051"
    seclang.kubewaf.io/phase: "5"
  name: crs-980051
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-REPORTING
    non-disruptive:
    - nonDisruptiveActionType: nolog
  markerAfter: LOG-REPORTING
  match:
  - collections:
    - arguments:
      - REPORTING_LEVEL
      name: TX
    operator:
      name: lt
      value: "4"
  metadata:
    comment: |
      -= Reporting Level 4 =- (Skip over reporting when tx.reporting_level is less than 4)
    id: 980051
    phase: "5"
  order: 980051
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-980-CORRELATION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "980170"
    seclang.kubewaf.io/order: "980170"
    seclang.kubewaf.io/phase: "5"
    seclang.kubewaf.io/tag.reporting: "true"
  name: crs-980170
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    non-disruptive:
    - nonDisruptiveActionType: noauditlog
  markerAfter: END-REPORTING
  match:
  - always-match: true
    operator:
      name: unconditionalMatch
    transformations:
    - none
  metadata:
    comment: |
      Inbound and outbound - all requests
      crs-linter:ignore:pass_nolog
    id: 980170
    message: |-
      Anomaly Scores: \
      (Inbound Scores: blocking=%{tx.blocking_inbound_anomaly_score}, detection=%{tx.detection_inbound_anomaly_score}, per_pl=%{tx.inbound_anomaly_score_pl1}-%{tx.inbound_anomaly_score_pl2}-%{tx.inbound_anomaly_score_pl3}-%{tx.inbound_anomaly_score_pl4}, threshold=%{tx.inbound_anomaly_score_threshold}) - \
      (Outbound Scores: blocking=%{tx.blocking_outbound_anomaly_score}, detection=%{tx.detection_outbound_anomaly_score}, per_pl=%{tx.outbound_anomaly_score_pl1}-%{tx.outbound_anomaly_score_pl2}-%{tx.outbound_anomaly_score_pl3}-%{tx.outbound_anomaly_score_pl4}, threshold=%{tx.outbound_anomaly_score_threshold}) - \
      (SQLI=%{tx.sql_injection_score}, XSS=%{tx.xss_score}, RFI=%{tx.rfi_score}, LFI=%{tx.lfi_score}, RCE=%{tx.rce_score}, PHPI=%{tx.php_injection_score}, HTTP=%{tx.http_violation_score}, SESS=%{tx.session_fixation_score}, COMBINED_SCORE=%{tx.anomaly_score})
    phase: "5"
    tags:
    - reporting
  order: 980170
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-980-CORRELATION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "980011"
    seclang.kubewaf.io/order: "980011"
    seclang.kubewaf.io/phase: "1"
  name: crs-980011
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-980-CORRELATION
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "1"
  metadata:
    id: 980011
    phase: "1"
  order: 980011
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-980-CORRELATION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "980012"
    seclang.kubewaf.io/order: "980012"
    seclang.kubewaf.io/phase: "2"
  name: crs-980012
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-980-CORRELATION
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "1"
  metadata:
    id: 980012
    phase: "2"
  order: 980012
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-980-CORRELATION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "980013"
    seclang.kubewaf.io/order: "980013"
    seclang.kubewaf.io/phase: "1"
  name: crs-980013
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-980-CORRELATION
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "2"
  metadata:
    comment: |+
      -= Paranoia Level 1 (default) =- (apply only when tx.detection_paranoia_level is sufficiently high: 1 or higher)

    id: 980013
    phase: "1"
  order: 980013
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-980-CORRELATION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "980014"
    seclang.kubewaf.io/order: "980014"
    seclang.kubewaf.io/phase: "2"
  name: crs-980014
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-980-CORRELATION
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "2"
  metadata:
    id: 980014
    phase: "2"
  order: 980014
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-980-CORRELATION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "980015"
    seclang.kubewaf.io/order: "980015"
    seclang.kubewaf.io/phase: "1"
  name: crs-980015
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-980-CORRELATION
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "3"
  metadata:
    comment: |+
      -= Paranoia Level 2 =- (apply only when tx.detection_paranoia_level is sufficiently high: 2 or higher)

    id: 980015
    phase: "1"
  order: 980015
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-980-CORRELATION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "980016"
    seclang.kubewaf.io/order: "980016"
    seclang.kubewaf.io/phase: "2"
  name: crs-980016
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-980-CORRELATION
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "3"
  metadata:
    id: 980016
    phase: "2"
  order: 980016
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-980-CORRELATION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "980017"
    seclang.kubewaf.io/order: "980017"
    seclang.kubewaf.io/phase: "1"
  name: crs-980017
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-980-CORRELATION
    non-disruptive:
    - nonDisruptiveActionType: nolog
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "4"
  metadata:
    comment: |+
      -= Paranoia Level 3 =- (apply only when tx.detection_paranoia_level is sufficiently high: 3 or higher)

    id: 980017
    phase: "1"
  order: 980017
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-980-CORRELATION.conf
    coreruleset/version: 4.27.0
    seclang.kubewaf.io/id: "980018"
    seclang.kubewaf.io/order: "980018"
    seclang.kubewaf.io/phase: "2"
  name: crs-980018
spec:
  actions:
    disruptive:
      disruptiveActionType: pass
    flow:
    - flowActionType: skipAfter
      value: END-RESPONSE-980-CORRELATION
    non-disruptive:
    - nonDisruptiveActionType: nolog
  markerAfter: END-RESPONSE-980-CORRELATION
  match:
  - collections:
    - arguments:
      - DETECTION_PARANOIA_LEVEL
      name: TX
    operator:
      name: lt
      value: "4"
  metadata:
    id: 980018
    phase: "2"
  order: 980018
